/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef ToF_VL53L0X_H
#define ToF_VL53L0X_H

#include "../../../BricRoboSketch/ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "ToF_VL53L0X.h"

void ToF_VL53L0X::ConfigParam(int IsLongRange, int speed)
{
}
  void ToF_VL53L0X::Run()
{
	ValueIF out;
    Rte_Write_out(out);

}
*/


/**
ToF距離センサー　VL53L0Xを使って距離計測する。
@author ike
@version 1.0
*/
class ToF_VL53L0X
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: VL53L0X sensor;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param IsLongRange	長距離の計測。まわりが暗いとき威力を発揮。
0=普通モード
1=長距離モード
	@param speed	計測間隔の時間
デフォルト＝33ms
短い=20ms
長い=200ms


	*/
	public: void ConfigParam(int IsLongRange, int speed);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Write_out(ValueIF) */
	BricRoboPortWrite(ValueIF,out);
};

/* Procedure Template
*/

#endif /* ToF_VL53L0X_H */
