/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */
#ifndef Const_H
#define Const_H

#include "../../../BricRoboSketch/ValueIF.h"

/*
void Const::ConfigParam(int value)
{
}
  */


/**
定数値をずっと出力する。
@author eguchi
@version 1.0
*/
class Const
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param value	
	*/
	public: void ConfigParam(int value);
	/*
	RunnableEntity
	*/
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Write_out(ValueIF) */
	BricRoboPortWrite(ValueIF,out);
};

/* Procedure Template
*/

#endif /* Const_H */
