/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */
#ifndef Telecom_H
#define Telecom_H

#include "../../../Common/CommandIF.h"
#include "../../../Common/NaviIF.h"

/*
void Telecom::ConfigParam(int dummy)
{
}
  void Telecom::RunRx()
{
	CommandIF command;
    Rte_Send_command(command);
	NaviIF navi;
    Rte_Read_navi(navi);

}
void Telecom::RunTx()
{
	CommandIF command;
    Rte_Send_command(command);
	NaviIF navi;
    Rte_Read_navi(navi);

}
*/


/**

@author eguchi
@version 1.0
*/
class Telecom
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param dummy	
	*/
	public: void ConfigParam(int dummy);
	/*
	RunnableEntity
	*/
	/**
	受信処理を行う。
	*/
	public: void RunRx();
	/**
	送信処理を行う。
	*/
	public: void RunTx();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Send_command(CommandIF) */
	BricRoboPortSend(CommandIF,command);
	/**
	
	*/
	/* Rte_Read_navi(NaviIF) */
	BricRoboPortRead(NaviIF,navi);
};

/* Procedure Template
*/

#endif /* Telecom_H */
