/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,EnumDataType.h.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef TeniboComMagic_H
#define TeniboComMagic_H



/**
ArduinoとRaspiがCOMで通信するとき、頭につける２バイトのマジックナンバー。この番号がついていないと正しいパケットとはみなさない。
@author ike
@version 1.0
*/
enum TeniboComMagic
{
	/**
	
	*/
	MAGIC_1 = 0xAA,
	/**
	
	*/
	MAGIC_2 = 0xBB,
};

#endif /* TeniboComMagic_H */
