/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef TeniboCommandIF_H
#define TeniboCommandIF_H

#include "TeniboCommnd.h"
#include "../Common/Parts/LedDriver/LedPattern.h"


/**
ロボットを制御するコマンド
@author eguchi
@version 1.0
*/
class TeniboCommandIF
{
	/*
	User Defined Attribute
	*/
	/**
	コマンド
	*/
	public: uint8_t cmd;
	/**
	パラメータ。値の意味はコマンドにより決定する。
	*/
	public: int16_t param1;
	/**
	パラメータ。値の意味はコマンドにより決定する。
	*/
	public: int16_t param2;
	/**
	パラメータ。値の意味はコマンドにより決定する。
	*/
	public: int16_t param3;
	/**
	
	*/
	public: int16_t param4;
	/**
	
	*/
	public: int16_t param5;
	/*
	User Defined Method
	*/
};

#endif /* TeniboCommandIF_H */
