/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,EnumDataType.h.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef TeniboStatus_H
#define TeniboStatus_H



/**

@author ike
@version 1.0
*/
enum TeniboStatus
{
	/**
	–â‘è‚ª‚È‚¯‚ê‚ÎON
	*/
	TS_OK = 0x0001,
	/**
	Ž©“®‰^“]‚È‚çON
	*/
	TS_AUTO = 0x0002,
};

#endif /* TeniboStatus_H */
