/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef TeniboNaviIF_H
#define TeniboNaviIF_H

#include "TeniboStatus.h"


/**
ロボットからプロポに通知するナビ情報
@author ike
@version 1.0
*/
class TeniboNaviIF
{
	/*
	User Defined Attribute
	*/
	/**
	電源バッテリ電圧。1,200は12.00V
	*/
	public: int16_t battery;
	/**
	ステータスビットの集合
	*/
	public: uint16_t status;
	/*
	User Defined Method
	*/
};

#endif /* TeniboNaviIF_H */
