/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */
#ifndef PositionSensor_H
#define PositionSensor_H

#include "../../../Common/PositionIF.h"

/*
void PositionSensor::ConfigParam(int dummy)
{
}
  void PositionSensor::Run()
{
	PositionIF out;
    Rte_Write_out(out);

}
*/


/**
SCL：A5ピン
SDA：A4ピン
INT：D2
I2Cを使ってMPU-6050と通信するので、この部品は1回しか使えない。
@author eguchi
@version 1.0
*/
class PositionSensor
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param dummy	
	*/
	public: void ConfigParam(int dummy);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	計測した姿勢
	*/
	/* Rte_Write_out(PositionIF) */
	BricRoboPortWrite(PositionIF,out);
};

/* Procedure Template
*/

#endif /* PositionSensor_H */
