/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef MS580314BA_H
#define MS580314BA_H

#include "../../../BricRoboSketch/ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "MS580314BA.h"

void MS580314BA::ConfigParam(int dummy)
{
}
  void MS580314BA::Run()
{
	ValueIF out;
    Rte_Write_out(out);

}
*/


/**
水深センサー
ArduinoのI2Cライブラリを使うのでピン設定はない。
@author ike
@version 1.0
*/
class MS580314BA
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param dummy	
	*/
	public: void ConfigParam(int dummy);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Write_out(ValueIF) */
	BricRoboPortWrite(ValueIF,out);
};

/* Procedure Template
*/

#endif /* MS580314BA_H */
