/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboRTE_Task.cc.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */

#include "stdafx.h"
#include "BricRoboRTE_Model.h"
#include "BricRoboTask.h"
void TASK_LED_Run()
{
	TopLevel.FRONTLED.Run();
}
void TASK_UI_Run()
{
	TopLevel.BALL.Run();
	TopLevel.BAT.Run();
}
void TASL_CTL_Run()
{
	TopLevel.RunRsv();
	TopLevel.RunSend();
}


/**
LED専用タスク。点滅を制御するので周期は速い。
@author eguchi
@version 1.0
*/
BricRoboTask TASK_LED = {10, 0, TASK_LED_Run};

/**
ユーザーIF用。100m秒ぐらいで十分だろう。
@author eguchi
@version 1.0
*/
BricRoboTask TASK_UI = {100, 1, TASK_UI_Run};

/**

@author ike
@version 1.0
*/
BricRoboTask TASL_CTL = {50, 1, TASL_CTL_Run};

BricRoboTask* taskList[3+1] =
{
	&TASK_LED,
	&TASK_UI,
	&TASL_CTL,
	(BricRoboTask*)0
};
