/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboCOM_API.cc.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */

#include "stdafx.h"
#include "BricRoboCOM_API.h"

ValueIF TaskCom_D1;	/*AB_in */
Std_ReturnType TaskCom_D1_status = RTE_E_NO_DATA;
HighLowIF TaskCom_D2;	/*BALL_in */
Std_ReturnType TaskCom_D2_status = RTE_E_NO_DATA;
ValueIF TaskCom_D3;	/*CTRL_battery */
Std_ReturnType TaskCom_D3_status = RTE_E_NO_DATA;
TeniboCommandIF TaskCom_D4;	/*CTRL_command */
Std_ReturnType TaskCom_D4_status = RTE_E_NO_DATA;
ValueIF TaskCom_D5;	/*FR_in */
Std_ReturnType TaskCom_D5_status = RTE_E_NO_DATA;
ValueIF TaskCom_D6;	/*FRONTLED_patternNo */
Std_ReturnType TaskCom_D6_status = RTE_E_NO_DATA;
ValueIF TaskCom_D7;	/*STR1_in */
Std_ReturnType TaskCom_D7_status = RTE_E_NO_DATA;
ValueIF TaskCom_D8;	/*STR2_in */
Std_ReturnType TaskCom_D8_status = RTE_E_NO_DATA;
TeniboNaviIF TaskCom_D9;	/*TEL_navi */
Std_ReturnType TaskCom_D9_status = RTE_E_NO_DATA;
