/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboCOM_API.h.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef ComsarCOM_API_H
#define ComsarCOM_API_H
#include "BricRoboCOM.h"

/*
Interface
*/
#include "../../BricRoboSketch/ValueIF.h"
#include "../../BricRoboSketch/HighLowIF.h"
#include "../../TeniboCommon/TeniboCommandIF.h"
#include "../../TeniboCommon/TeniboNaviIF.h"

/*
COM API
*/
#define COM_Write_D1(v)	COM_Write(TaskCom_D1,v,TaskCom_D1_status)
#define COM_Read_D1(v)	COM_Read(TaskCom_D1,v,TaskCom_D1_status)
#define COM_Send_D1(v)	COM_Send(TaskCom_D1,v,TaskCom_D1_status)
#define COM_Receive_D1(v)	COM_Receive(TaskCom_D1,v,TaskCom_D1_status)
#define COM_Write_D2(v)	COM_Write(TaskCom_D2,v,TaskCom_D2_status)
#define COM_Read_D2(v)	COM_Read(TaskCom_D2,v,TaskCom_D2_status)
#define COM_Send_D2(v)	COM_Send(TaskCom_D2,v,TaskCom_D2_status)
#define COM_Receive_D2(v)	COM_Receive(TaskCom_D2,v,TaskCom_D2_status)
#define COM_Write_D3(v)	COM_Write(TaskCom_D3,v,TaskCom_D3_status)
#define COM_Read_D3(v)	COM_Read(TaskCom_D3,v,TaskCom_D3_status)
#define COM_Send_D3(v)	COM_Send(TaskCom_D3,v,TaskCom_D3_status)
#define COM_Receive_D3(v)	COM_Receive(TaskCom_D3,v,TaskCom_D3_status)
#define COM_Write_D4(v)	COM_Write(TaskCom_D4,v,TaskCom_D4_status)
#define COM_Read_D4(v)	COM_Read(TaskCom_D4,v,TaskCom_D4_status)
#define COM_Send_D4(v)	COM_Send(TaskCom_D4,v,TaskCom_D4_status)
#define COM_Receive_D4(v)	COM_Receive(TaskCom_D4,v,TaskCom_D4_status)
#define COM_Write_D5(v)	COM_Write(TaskCom_D5,v,TaskCom_D5_status)
#define COM_Read_D5(v)	COM_Read(TaskCom_D5,v,TaskCom_D5_status)
#define COM_Send_D5(v)	COM_Send(TaskCom_D5,v,TaskCom_D5_status)
#define COM_Receive_D5(v)	COM_Receive(TaskCom_D5,v,TaskCom_D5_status)
#define COM_Write_D6(v)	COM_Write(TaskCom_D6,v,TaskCom_D6_status)
#define COM_Read_D6(v)	COM_Read(TaskCom_D6,v,TaskCom_D6_status)
#define COM_Send_D6(v)	COM_Send(TaskCom_D6,v,TaskCom_D6_status)
#define COM_Receive_D6(v)	COM_Receive(TaskCom_D6,v,TaskCom_D6_status)
#define COM_Write_D7(v)	COM_Write(TaskCom_D7,v,TaskCom_D7_status)
#define COM_Read_D7(v)	COM_Read(TaskCom_D7,v,TaskCom_D7_status)
#define COM_Send_D7(v)	COM_Send(TaskCom_D7,v,TaskCom_D7_status)
#define COM_Receive_D7(v)	COM_Receive(TaskCom_D7,v,TaskCom_D7_status)
#define COM_Write_D8(v)	COM_Write(TaskCom_D8,v,TaskCom_D8_status)
#define COM_Read_D8(v)	COM_Read(TaskCom_D8,v,TaskCom_D8_status)
#define COM_Send_D8(v)	COM_Send(TaskCom_D8,v,TaskCom_D8_status)
#define COM_Receive_D8(v)	COM_Receive(TaskCom_D8,v,TaskCom_D8_status)
#define COM_Write_D9(v)	COM_Write(TaskCom_D9,v,TaskCom_D9_status)
#define COM_Read_D9(v)	COM_Read(TaskCom_D9,v,TaskCom_D9_status)
#define COM_Send_D9(v)	COM_Send(TaskCom_D9,v,TaskCom_D9_status)
#define COM_Receive_D9(v)	COM_Receive(TaskCom_D9,v,TaskCom_D9_status)

/*
COM Buffer
*/
extern ValueIF TaskCom_D1;
extern Std_ReturnType TaskCom_D1_status;
extern HighLowIF TaskCom_D2;
extern Std_ReturnType TaskCom_D2_status;
extern ValueIF TaskCom_D3;
extern Std_ReturnType TaskCom_D3_status;
extern TeniboCommandIF TaskCom_D4;
extern Std_ReturnType TaskCom_D4_status;
extern ValueIF TaskCom_D5;
extern Std_ReturnType TaskCom_D5_status;
extern ValueIF TaskCom_D6;
extern Std_ReturnType TaskCom_D6_status;
extern ValueIF TaskCom_D7;
extern Std_ReturnType TaskCom_D7_status;
extern ValueIF TaskCom_D8;
extern Std_ReturnType TaskCom_D8_status;
extern TeniboNaviIF TaskCom_D9;
extern Std_ReturnType TaskCom_D9_status;

#endif /* ComsarCOM_API_H */
