/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++.BricRoboRTE_API.h.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef ComsarRTE_API_H
#define ComsarRTE_API_H

/*
Interface
*/
#include "../../BricRoboSketch/ValueIF.h"
#include "../../BricRoboSketch/HighLowIF.h"
#include "../../TeniboCommon/TeniboCommandIF.h"
#include "../../TeniboCommon/TeniboNaviIF.h"

/*
RTE API (SenderReceiverInterface)
*/
extern Std_ReturnType Rte_Receive_FR_deadZone(ValueIF& v);
extern Std_ReturnType Rte_Receive_STR1_deadZone(ValueIF& v);
extern Std_ReturnType Rte_Receive_STR2_deadZone(ValueIF& v);

/*
RTE API (ProcedureCallInterface)
*/


#endif /* ComsarRTE_API_H */
