/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboRTE_Model.h.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef ComsarRTE_Model_H
#define ComsarRTE_Model_H

/*
Used BricRobo CompositionType
*/
#include "../TeniboArduino.h"

extern TeniboArduino TopLevel;


extern void BricRoboRTE_ConnectRteApi();
extern void BricRoboRTE_ConfigParam();

#endif /* ComsarRTE_Model_H */
