/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboRTE_API.cc.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */


#include "stdafx.h"
#include "BricRoboCOM_API.h"
#include "BricRoboRTE_API.h"
#include "BricRoboRTE_Model.h"

/*
RTE API (SenderReceiverInterface)
*/
/* RteApiID=54 */
Std_ReturnType Rte_Receive_FR_deadZone(ValueIF& v)
{
	return (Std_ReturnType)(COM_NotConnected(v));
}

/* RteApiID=57 */
Std_ReturnType Rte_Receive_STR1_deadZone(ValueIF& v)
{
	return (Std_ReturnType)(COM_NotConnected(v));
}

/* RteApiID=60 */
Std_ReturnType Rte_Receive_STR2_deadZone(ValueIF& v)
{
	return (Std_ReturnType)(COM_NotConnected(v));
}

/*
RTE API (ProcedureCallInterface Assembly)
*/
/*
RTE API (ProcedureCallInterface Delegate Provider)
*/
/*
RTE API (ProcedureCallInterface Delegate Requester)
*/

