/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboRTE_Model.cc.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */

#include "stdafx.h"
#include "BricRoboCOM_API.h"
#include "BricRoboRTE_API.h"
#include "BricRoboRTE_Model.h"
/*
TopLevel
*/
TeniboArduino TopLevel;

/*
ConfigParam
*/
void BricRoboRTE_ConfigParam()
{
	TopLevel.AB.ConfigParam(0, 10, 5);
	TopLevel.BALL.ConfigParam(3);
	TopLevel.BAT.ConfigParam(1, 0.917);
	TopLevel.FR.ConfigParam(11, 0, 100);
	TopLevel.FRONTLED.ConfigParam(2);
	TopLevel.STR1.ConfigParam(5, 0, 90);
	TopLevel.STR2.ConfigParam(6, 0, 90);
	TopLevel.TEL.ConfigParam(0);
}

/*
RTE-COM
*/
void BricRoboRTE_ConnectRteApi()
{
	TopLevel.AB._portIF_in = &TaskCom_D1;
	TopLevel.AB._portST_in = &TaskCom_D1_status;
	TopLevel.CTRL._portIF_accel = &TaskCom_D1;
	TopLevel.CTRL._portST_accel = &TaskCom_D1_status;
	TopLevel.BALL._portIF_in = &TaskCom_D2;
	TopLevel.BALL._portST_in = &TaskCom_D2_status;
	TopLevel.CTRL._portIF_ballPick = &TaskCom_D2;
	TopLevel.CTRL._portST_ballPick = &TaskCom_D2_status;
	TopLevel.CTRL._portIF_battery = &TaskCom_D3;
	TopLevel.CTRL._portST_battery = &TaskCom_D3_status;
	TopLevel.BAT._portIF_volt = &TaskCom_D3;
	TopLevel.BAT._portST_volt = &TaskCom_D3_status;
	TopLevel.CTRL._portIF_command = &TaskCom_D4;
	TopLevel.CTRL._portST_command = &TaskCom_D4_status;
	TopLevel.TEL._portIF_command = &TaskCom_D4;
	TopLevel.TEL._portST_command = &TaskCom_D4_status;
	TopLevel.FR._portIF_in = &TaskCom_D5;
	TopLevel.FR._portST_in = &TaskCom_D5_status;
	TopLevel.AB._portIF_out = &TaskCom_D5;
	TopLevel.AB._portST_out = &TaskCom_D5_status;
	TopLevel.FRONTLED._portIF_patternNo = &TaskCom_D6;
	TopLevel.FRONTLED._portST_patternNo = &TaskCom_D6_status;
	TopLevel.CTRL._portIF_frontLed = &TaskCom_D6;
	TopLevel.CTRL._portST_frontLed = &TaskCom_D6_status;
	TopLevel.STR1._portIF_in = &TaskCom_D7;
	TopLevel.STR1._portST_in = &TaskCom_D7_status;
	TopLevel.CTRL._portIF_steer1 = &TaskCom_D7;
	TopLevel.CTRL._portST_steer1 = &TaskCom_D7_status;
	TopLevel.STR2._portIF_in = &TaskCom_D8;
	TopLevel.STR2._portST_in = &TaskCom_D8_status;
	TopLevel.CTRL._portIF_steer2 = &TaskCom_D8;
	TopLevel.CTRL._portST_steer2 = &TaskCom_D8_status;
	TopLevel.TEL._portIF_navi = &TaskCom_D9;
	TopLevel.TEL._portST_navi = &TaskCom_D9_status;
	TopLevel.CTRL._portIF_navi = &TaskCom_D9;
	TopLevel.CTRL._portST_navi = &TaskCom_D9_status;
	TopLevel.FR._portAPI_deadZone = Rte_Receive_FR_deadZone;
	TopLevel.STR1._portAPI_deadZone = Rte_Receive_STR1_deadZone;
	TopLevel.STR2._portAPI_deadZone = Rte_Receive_STR2_deadZone;
}
