/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef CommandIFAmp_H
#define CommandIFAmp_H

#include "CommandIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "CommandIFAmp.h"

void CommandIFAmp::Run()
{
	CommandIF in;
    Rte_Receive_in(in);
	CommandIF out;
    Rte_Send_out(out);

}
*/


/**

@author eguchi
@version 1.0
*/
class CommandIFAmp
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Receive_in(CommandIF) */
	BricRoboPortReceiveQueue(CommandIF,in,2);
	/**
	
	*/
	/* Rte_Send_out(CommandIF) */
	BricRoboPortSend(CommandIF,out);
};

/* Procedure Template
*/

#endif /* CommandIFAmp_H */
