/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef EventIF_H
#define EventIF_H



/**
イベントが発生したことを表す。メンバはない。
@author eguchi
@version 1.0
*/
class EventIF
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
};

#endif /* EventIF_H */
