/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,EnumDataType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef FishStatusBit_H
#define FishStatusBit_H



/**

@author eguchi
@version 1.0
*/
enum FishStatusBit
{
	/**
	照明ON
	*/
	FS_LIGHT_ON = 0x01,
	/**
	ビデオ録画中（チャネル0）
	*/
	FS_VIDEO_REC_OVL = 0x02,
	/**
	ビデオ録画中（チャネル１）
	*/
	FS_VIDEO_REC_ORG = 0x04,
	/**
	緊急対処中
	*/
	FS_EMERGENCY = 0x40,
	/**
	セーフティモードのON/OFF
	*/
	FS_SAFETY_MODE = 0x80,
};

#endif /* FishStatusBit_H */
