/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef IntIF_H
#define IntIF_H



/**
’lInt‚ðˆµ‚¤IF
@author eguchi
@version 1.0
*/
class IntIF
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	public: int value;
	/*
	User Defined Method
	*/
};

#endif /* IntIF_H */
