/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,EnumDataType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef MAGIC_NO_H
#define MAGIC_NO_H



/**
通信の際、先頭に浸けるマジックナンバー。これが一致すれば正しいパケットとみなす。
@author eguchi
@version 1.0
*/
enum MAGIC_NO
{
	/**
	先頭1バイト目の値。
	*/
	MAGIC_1 = 0xAA,
	/**
	先頭2バイト目の値。
	*/
	MAGIC_2 = 0xBB,
};

#endif /* MAGIC_NO_H */
