/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef NaviIFAmp_H
#define NaviIFAmp_H

#include "NaviIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "NaviIFAmp.h"

void NaviIFAmp::Run()
{
	NaviIF in;
    Rte_Read_in(in);
	NaviIF out;
    Rte_Write_out(out);

}
*/


/**

@author eguchi
@version 1.0
*/
class NaviIFAmp
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Read_in(NaviIF) */
	BricRoboPortRead(NaviIF,in);
	/**
	
	*/
	/* Rte_Write_out(NaviIF) */
	BricRoboPortWrite(NaviIF,out);
};

/* Procedure Template
*/

#endif /* NaviIFAmp_H */
