/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef NaviIF_H
#define NaviIF_H

#include "MAGIC_NO.h"
#include "FishStatusBit.h"
#include "PositionIF.h"


/**
ロボットの状態を知らせる
@author eguchi
@version 1.0
*/
class NaviIF
{
	/*
	User Defined Attribute
	*/
	/**
	胸ビレの角度の値(-90..+90)
	*/
	public: int8_t pecFin;
	/**
	尾ビレの角度の値(-90..+90)
	*/
	public: int8_t tailFin;
	/**
	推進力の値(0-100)
	*/
	public: int8_t jetPower;
	/**
	
	*/
	public: uint8_t status;
	/**
	水圧計の値（生値）
	*/
	public: int16_t waterPressure;
	/**
	水底からの距離(cm)
	*/
	public: int16_t bottomDistance;
	/**
	浸水センサーの値(0-1023)
	*/
	public: int16_t flood;
	/**
	速度（cm/秒）
	*/
	public: uint8_t speed;
	/**
	cm単位
	*/
	public: uint16_t mile;
	/**
	
	*/
	public: PositionIF position;
	/*
	User Defined Method
	*/
};

#endif /* NaviIF_H */
