/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef PidParamIF_H
#define PidParamIF_H



/**
PIDパラメタ。１は分子、２は分母。
@author ike
@version 1.0
*/
class PidParamIF
{
	/*
	User Defined Attribute
	*/
	/**
	P成分の分子
	*/
	public: int16_t p1;
	/**
	P成分の分母
	*/
	public: int16_t p2;
	/**
	I成分の分子
	*/
	public: int16_t i1;
	/**
	I成分の分母
	*/
	public: int16_t i2;
	/**
	D成分の分子
	*/
	public: int16_t d1;
	/**
	D成分の分母
	*/
	public: int16_t d2;
	/*
	User Defined Method
	*/
};

#endif /* PidParamIF_H */
