/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,EnumDataType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef PositionStatus_H
#define PositionStatus_H



/**
ジャイロセンサーの状態
@author eguchi
@version 1.0
*/
enum PositionStatus
{
	/**
	準備中
	*/
	POS_NOT_READY = 0,
	/**
	稼働中

	*/
	POS_WORKING = 1,
	/**
	エラー
	*/
	POS_ERROR = -1,
};

#endif /* PositionStatus_H */
