/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef PositionIF_H
#define PositionIF_H

#include "PositionStatus.h"


/**
姿勢のYow、Roll、Pitch
@author eguchi
@version 1.0
*/
class PositionIF
{
	/*
	User Defined Attribute
	*/
	/**
	進行方向の向き（-180..+180）
0x8000のときはERRORを示す。
0x7FFFのときは準備中を示す。
	*/
	public: int16_t yaw;
	/**
	左右の傾き（-180..+180）
	*/
	public: int16_t roll;
	/**
	前後の傾き（-180..+180）
	*/
	public: int16_t pitch;
	/**
	
	*/
	public: int8_t status;
	/*
	User Defined Method
	*/
};

#endif /* PositionIF_H */
