/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef SetCamIF_H
#define SetCamIF_H



/**

@author eguchi
@version 1.0
*/
class SetCamIF
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	public: int camNo;
	/*
	User Defined Method
	*/
};

#endif /* SetCamIF_H */
