/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef TimeSpanIF_H
#define TimeSpanIF_H



/**
Œo‰ßŽžŠÔ‚ð•\‚·
@author eguchi
@version 1.0
*/
class TimeSpanIF
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	public: System.TimeSpan value;
	/*
	User Defined Method
	*/
};

#endif /* TimeSpanIF_H */
