/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef NoiseFilter_H
#define NoiseFilter_H

#include "../../../BricRoboSketch/ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "NoiseFilter.h"

void NoiseFilter::ConfigParam(int16_t limit)
{
}
  void NoiseFilter::Run()
{
	ValueIF in;
    Rte_Read_in(in);
	ValueIF out;
    Rte_Write_out(out);

}
*/


/**
極端な値を捨てる
@author ike
@version 1.0
*/
class NoiseFilter
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: int16_t _limit;
	/**
	いま有効な値
	*/
	private: int16_t _current;
	/**
	リミットを超えた捨てられた値
	*/
	private: int16_t _lost;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param limit	
	*/
	public: void ConfigParam(int16_t limit);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Read_in(ValueIF) */
	BricRoboPortRead(ValueIF,in);
	/**
	
	*/
	/* Rte_Write_out(ValueIF) */
	BricRoboPortWrite(ValueIF,out);
};

/* Procedure Template
*/

#endif /* NoiseFilter_H */
