/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2014/02/22 14:08:27
	Generater Name:BricRoboGen Ver:1.6.0.305  
 */
#ifndef AddHighLow_H
#define AddHighLow_H

#include "HighLowIF.h"

/*
void AddHighLow::ConfigParam(uint8_t init)
{
}
  void AddHighLow::Run()
{
	HighLowIF carry;
    Rte_Write_carry(carry);
	HighLowIF in;
    Rte_Read_in(in);
	HighLowIF out;
    Rte_Write_out(out);

}
*/


/**
1ビットを記憶し、入力した1ビットと、加算演算を行う。結果を出力し、キャリー発生の有無もビット出力する。
@author ike
@version 1.0
*/
class AddHighLow
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: uint8_t _bit;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param init	初期に保持する値。
	*/
	public: void ConfigParam(uint8_t init);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	2つのビットを加算してキャリーオーバーしたビット
	*/
	/* Rte_Write_carry(HighLowIF) */
	BricRoboPortWrite(HighLowIF,carry);
	/**
	入力ビット
	*/
	/* Rte_Read_in(HighLowIF) */
	BricRoboPortRead(HighLowIF,in);
	/**
	出力ビット
	*/
	/* Rte_Write_out(HighLowIF) */
	BricRoboPortWrite(HighLowIF,out);
};

/* Procedure Template
*/

#endif /* AddHighLow_H */
