/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 21:46:10
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef AnalogOut_H
#define AnalogOut_H

#include "ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "AnalogOut.h"

void AnalogOut::ConfigParam(uint8_t pin)
{
}
  void AnalogOut::Run()
{
	ValueIF in;
    Rte_Read_in(in);

}
*/


/**
指定したアナログピンから値をPWMで出力します。
0は常にKOで、255は常にON(HI)です。
@author ike
@version 1.0
*/
class AnalogOut
{
	/*
	User Defined Attribute
	*/
	/**
	ピン番号を保持する。
	*/
	private: uint8_t _pin;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	アナログピン番号を指定します。
	*/
	public: void ConfigParam(uint8_t pin);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	LEDを光らせる命令。
	*/
	/* Rte_Read_in(ValueIF) */
	BricRoboPortRead(ValueIF,in);
};

/* Procedure Template
*/

#endif /* AnalogOut_H */
