/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 21:46:10
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef AnalogIn_H
#define AnalogIn_H

#include "ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "AnalogIn.h"

void AnalogIn::ConfigParam(uint8_t pin)
{
}
  void AnalogIn::Run()
{
	ValueIF out;
    Rte_Write_out(out);

}
*/


/**
指定したアナログピンから値を読み取ります。
読み取った値の範囲は0-1023です。
@author ike
@version 1.0
*/
class AnalogIn
{
	/*
	User Defined Attribute
	*/
	/**
	ピン番号を保持する。
	*/
	private: uint8_t _pin;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	アナログピン番号を指定します。
	*/
	public: void ConfigParam(uint8_t pin);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	LEDを光らせる命令。
	*/
	/* Rte_Write_out(ValueIF) */
	BricRoboPortWrite(ValueIF,out);
};

/* Procedure Template
*/

#endif /* AnalogIn_H */
