/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 21:46:10
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef DigitalOut_H
#define DigitalOut_H

#include "HighLowIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "DigitalOut.h"

void DigitalOut::ConfigParam(uint8_t pin)
{
}
  void DigitalOut::Run()
{
	HighLowIF in;
    Rte_Read_in(in);

}
*/


/**
指定したデジタルピンを出力モードにし、値を出力します。
@author ike
@version 1.0
*/
class DigitalOut
{
	/*
	User Defined Attribute
	*/
	/**
	ピン番号を保持する。
	*/
	private: uint8_t _pin;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	出力ピン番号を指定します。
	*/
	public: void ConfigParam(uint8_t pin);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	LEDを光らせる命令。
	*/
	/* Rte_Read_in(HighLowIF) */
	BricRoboPortRead(HighLowIF,in);
};

/* Procedure Template
*/

#endif /* DigitalOut_H */
