/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 21:46:10
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef DigitalIn_H
#define DigitalIn_H

#include "HighLowIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "DigitalIn.h"

void DigitalIn::ConfigParam(uint8_t pin)
{
}
  void DigitalIn::Run()
{
	HighLowIF out;
    Rte_Write_out(out);

}
*/


/**
指定したデジタルピンを入力モードにし、読み取った値を出力します。
@author ike
@version 1.0
*/
class DigitalIn
{
	/*
	User Defined Attribute
	*/
	/**
	ピン番号を保持する。
	*/
	private: uint8_t _pin;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	デジタルピン番号を指定します。
	*/
	public: void ConfigParam(uint8_t pin);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	LEDを光らせる命令。
	*/
	/* Rte_Write_out(HighLowIF) */
	BricRoboPortWrite(HighLowIF,out);
};

/* Procedure Template
*/

#endif /* DigitalIn_H */
