/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 21:46:10
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef HighLowWave_H
#define HighLowWave_H

#include "HighLowIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "HighLowWave.h"

void HighLowWave::ConfigParam(uint8_t lastState)
{
}
  void HighLowWave::Run()
{
	HighLowIF out;
    Rte_Write_out(out);

}
*/


/**
HIGHとLOWを交互に繰り返す矩形波を出力します。
@author ike
@version 1.0
*/
class HighLowWave
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: uint8_t _lastState;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param lastState	最後の状態を指定します。次に駆動すると反対の信号を出力します。
	*/
	public: void ConfigParam(uint8_t lastState);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Write_out(HighLowIF) */
	BricRoboPortWrite(HighLowIF,out);
};

/* Procedure Template
*/

#endif /* HighLowWave_H */
