/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 21:46:10
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef HighLowIF_H
#define HighLowIF_H



/**
HIGHまたはLOWを伝えるインタフェース。
@author ike
@version 1.0
*/
class HighLowIF
{
	/*
	User Defined Attribute
	*/
	/**
	HI/LOWの値
	*/
	public: uint8_t value;
	/*
	User Defined Method
	*/
};

#endif /* HighLowIF_H */
