/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2014/02/22 14:08:27
	Generater Name:BricRoboGen Ver:1.6.0.305  
 */
#ifndef HighLowInverter_H
#define HighLowInverter_H

#include "HighLowIF.h"

/*
void HighLowInverter::Run()
{
	HighLowIF in;
    Rte_Read_in(in);
	HighLowIF out;
    Rte_Write_out(out);

}
*/


/**
入力したビットを反転して出力します。
@author ike
@version 1.0
*/
class HighLowInverter
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Read_in(HighLowIF) */
	BricRoboPortRead(HighLowIF,in);
	/**
	
	*/
	/* Rte_Write_out(HighLowIF) */
	BricRoboPortWrite(HighLowIF,out);
};

/* Procedure Template
*/

#endif /* HighLowInverter_H */
