/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2014/01/07 11:14:10
	Generater Name:BricRoboGen Ver:1.6.0.302  
 */
#ifndef PilotLED_H
#define PilotLED_H



/**
パイロットランプのLEDを点滅させる。
@author ike
@version 1.0
*/
class PilotLED
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: bool _on;
	/**
	
	*/
	private: int _pin;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	
	*/
	public: void ConfigParam(int pin);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
};

/* Procedure Template
*/

#endif /* PilotLED_H */
