/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 21:46:10
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef ValueIF_H
#define ValueIF_H



/**
一般的な値(int16)を伝えるインタフェース。
@author ike
@version 1.0
*/
class ValueIF
{
	/*
	User Defined Attribute
	*/
	/**
	値
	*/
	public: int16_t value;
	/*
	User Defined Method
	*/
};

#endif /* ValueIF_H */
