/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef SwimControllerIF_H
#define SwimControllerIF_H



/**
機体の姿勢を制御する指令値
@author ike
@version 1.0
*/
class SwimControllerIF
{
	/*
	User Defined Attribute
	*/
	/**
	ダイブパワー
-100 .. +100
	*/
	public: int8_t dive;
	/**
	ロールパワー
-100 .. +100
	*/
	public: int8_t roll;
	/**
	前進後進パワー
-100 .. +100
	*/
	public: int8_t forward;
	/**
	ターンパワー
-100 .. +100
	*/
	public: int8_t turn;
	/*
	User Defined Method
	*/
};

#endif /* SwimControllerIF_H */
