/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef LedMiniDriver_H
#define LedMiniDriver_H

#include "../../../BricRoboSketch/ValueIF.h"
#include "LedMiniPattern.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "LedMiniDriver.h"

void LedMiniDriver::ConfigParam(int8_t pin)
{
}
  void LedMiniDriver::Run()
{
	ValueIF patternNo;
    Rte_Receive_patternNo(patternNo);

}
*/


/**

@author eguchi
@version 1.0
*/
class LedMiniDriver
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: int8_t _pin;
	/**
	LedPatternの番号
	*/
	private: int8_t _no;
	/**
	
	*/
	private: int8_t _row;
	/**
	
	*/
	private: uint8_t _hiLow;
	/**
	
	*/
	private: uint8_t _times;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	LEDを駆動するArduinoのピン番号
	*/
	public: void ConfigParam(int8_t pin);
	/*
	RunnableEntity
	*/
	/**
	10m秒周期で呼び出すこと。
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Receive_patternNo(ValueIF) */
	BricRoboPortReceive(ValueIF,patternNo);
};

/* Procedure Template
*/

#endif /* LedMiniDriver_H */
