/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,EnumDataType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef LedMiniPattern_H
#define LedMiniPattern_H



/**

@author eguchi
@version 1.0
*/
enum LedMiniPattern
{
	/**
	
	*/
	ALL_OFF = 0,
	/**
	
	*/
	ALL_ON = 1,
	/**
	
	*/
	STATE_STANDBY = 2,
	/**
	
	*/
	STATE_CTL = 3,
	/**
	
	*/
	STATE_ERROR = 4,
};

#endif /* LedMiniPattern_H */
