/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef LedPatternOuter_H
#define LedPatternOuter_H

#include "../../../BricRoboSketch/ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "LedPatternOuter.h"

void LedPatternOuter::Out(int8_t ptn)
{
}
  */


/**
LEDのパターン番号を出力する。
@author ike
@version 1.0
*/
class LedPatternOuter
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/**
	
	@param ptn	
	*/
	public: void Out(int8_t ptn);
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/*
	RunnableEntity
	*/
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Send_out(ValueIF) */
	BricRoboPortSend(ValueIF,out);
};

/* Procedure Template
*/

#endif /* LedPatternOuter_H */
