/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,EnumDataType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef LedPattern_H
#define LedPattern_H



/**

@author eguchi
@version 1.0
*/
enum LedPattern
{
	/**
	
	*/
	LED_0 = 0,
	/**
	
	*/
	LED_1 = 1,
	/**
	
	*/
	LED_2 = 2,
	/**
	
	*/
	LED_3 = 3,
	/**
	
	*/
	LED_4 = 4,
	/**
	
	*/
	LED_5 = 5,
	/**
	
	*/
	LED_6 = 6,
	/**
	
	*/
	LED_7 = 7,
	/**
	
	*/
	LED_8 = 8,
	/**
	
	*/
	LED_9 = 9,
	/**
	
	*/
	ALL_OFF = 10,
	/**
	
	*/
	ALL_ON = 11,
	/**
	
	*/
	STATE_STANDBY = 12,
	/**
	
	*/
	STATE_CTL = 13,
	/**
	
	*/
	STATE_ERROR = 14,
	/**
	1回だけフラッシュする
	*/
	ONESHOT_FLASH = 15,
	/**
	自律航行中
	*/
	STATE_AUTO = 16,
};

#endif /* LedPattern_H */
