/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,ClassDataType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef TcpServer_H
#define TcpServer_H



/**

@author eguchi
@version 1.0
*/
class TcpServer
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/**
	
	*/
	public:  TcpServer();
	/**
	
	@param portNo	
	*/
	public: void Start(int portNo);
	/**
	
	*/
	public: void Stop();
	/**
	
	@param result	
	*/
	private: void HandleAccept(IAsyncResult result);
};

#endif /* TcpServer_H */
