/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef FloodSensor_H
#define FloodSensor_H

#include "../../../BricRoboSketch/ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "FloodSensor.h"

void FloodSensor::ConfigParam(int8_t pin)
{
}
  void FloodSensor::Run()
{
	ValueIF value;
    Rte_Write_value(value);

}
*/


/**
AD変換して抵抗値を測る。

@author eguchi
@version 1.0
*/
class FloodSensor
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: int8_t _pin;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	使用するアナログピン番号
	*/
	public: void ConfigParam(int8_t pin);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	AD変換した値。
	*/
	/* Rte_Write_value(ValueIF) */
	BricRoboPortWrite(ValueIF,value);
};

/* Procedure Template
*/

#endif /* FloodSensor_H */
