/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef EscDriver_H
#define EscDriver_H

#include "../../../BricRoboSketch/ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "EscDriver.h"

void EscDriver::ConfigParam(int8_t pin, int16_t revise, int16_t plusePower, int8_t counter)
{
}
  void EscDriver::Run()
{
	ValueIF in;
    Rte_Read_in(in);

}
*/


/**
ブラシレスモーター用ESCドライバ
ｱ1000で制御。


@author eguchi
@version 1.0
*/
class EscDriver
{
	/*
	User Defined Attribute
	*/
	/**
	入力に掛ける値。１なら正転、-1なら逆転
	*/
	private: int16_t _revise;
	/**
	
	*/
	private: Servo _servo;
	/**
	PWM制御するためのタイマ。0-100の間をカウントする。
	*/
	private: int8_t _counter;
	/**
	PWM制御するとき、ONの時にESCに掛ける値。
	*/
	private: int16_t _plusePower;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	PWMで使うピン番号
	@param revise	
	@param plusePower	PWM制御するとき、ONの時にESCに掛ける値。
	@param counter	カウンタの初期値。
	*/
	public: void ConfigParam(int8_t pin, int16_t revise, int16_t plusePower, int8_t counter);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Read_in(ValueIF) */
	BricRoboPortRead(ValueIF,in);
};

/* Procedure Template
*/

#endif /* EscDriver_H */
