/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef Camera_H
#define Camera_H

#include "ImageFrame.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "Camera.h"

void Camera::ConfigParam(int camNo, int width, int height)
{
}
  void Camera::Run()
{
	ImageFrame image;
    Rte_Send_image(image);

}
*/


/**
Webカメラ。番号を指定して複数台から1台を決定。キャプチャサイズを指定する。
@author eguchi
@version 1.0
*/
class Camera
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: CvCapture _cap;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param camNo	
	@param width	
	@param height	
	*/
	public: void ConfigParam(int camNo, int width, int height);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Send_image(ImageFrame) */
	BricRoboPortSend(ImageFrame,image);
};

/* Procedure Template
*/

#endif /* Camera_H */
