/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef ImageFrame_H
#define ImageFrame_H



/**
ビデオの1フレーム
@author eguchi
@version 1.0
*/
class ImageFrame
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	public: IplImage img;
	/*
	User Defined Method
	*/
};

#endif /* ImageFrame_H */
