/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef SwimCmd_H
#define SwimCmd_H

#include "SwimMode.h"
#include "../../../Common/JellyFish/JellyFishNavi.h"


/**
機体の姿勢を制御する指令値
@author ike
@version 1.0
*/
class SwimCmd
{
	/*
	User Defined Attribute
	*/
	/**
	モード。SwimMode型。
	*/
	public: uint8_t mode;
	/**
	目標のナビ値。
	*/
	public: JellyFishNavi navi;
	/*
	User Defined Method
	*/
};

#endif /* SwimCmd_H */
