/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2015/01/17 15:11:40
	Generater Name:BricRoboGen Ver:1.6.1.326  
 */
#ifndef LedControler_H
#define LedControler_H

#include "../../BricRoboSketch/ValueIF.h"

/*
void LedControler::ConfigParam(int pin)
{
}
  void LedControler::Run()
{
	ValueIF patternNo;
    Rte_Receive_patternNo(patternNo);

}
*/


/**

@author eguchi
@version 1.0
*/
class LedControler
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: int _pin;
	/**
	
	*/
	private: int _no;
	/**
	
	*/
	private: int _row;
	/**
	
	*/
	private: int _hiLow;
	/**
	
	*/
	private: int _times;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	LEDを駆動するArduinoのピン番号
	*/
	public: void ConfigParam(int pin);
	/*
	RunnableEntity
	*/
	/**
	10m秒周期で呼び出すこと。
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Receive_patternNo(ValueIF) */
	BricRoboPortReceive(ValueIF,patternNo);
};

/* Procedure Template
*/

#endif /* LedControler_H */
