/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2014/10/27 11:06:46
	Generater Name:BricRoboGen Ver:1.6.0.321  
 */
#ifndef Robot_H
#define Robot_H


/*
void Robot::ConfigParam(int dummy)
{
}
  void Robot::Run()
{

}
*/


/**

@author eguchi
@version 1.0
*/
class Robot
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param dummy	
	*/
	public: void ConfigParam(int dummy);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
};

/* Procedure Template
*/

#endif /* Robot_H */
