// Generated by gencpp from file ShoesTranspoterPkg/transpoter_status.msg
// DO NOT EDIT!


#ifndef SHOESTRANSPOTERPKG_MESSAGE_TRANSPOTER_STATUS_H
#define SHOESTRANSPOTERPKG_MESSAGE_TRANSPOTER_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ShoesTranspoterPkg
{
template <class ContainerAllocator>
struct transpoter_status_
{
  typedef transpoter_status_<ContainerAllocator> Type;

  transpoter_status_()
    : transpoter_id(0)
    , transpoter_location(0)
    , transpoter_shoes(0)  {
    }
  transpoter_status_(const ContainerAllocator& _alloc)
    : transpoter_id(0)
    , transpoter_location(0)
    , transpoter_shoes(0)  {
  (void)_alloc;
    }



   typedef uint8_t _transpoter_id_type;
  _transpoter_id_type transpoter_id;

   typedef uint8_t _transpoter_location_type;
  _transpoter_location_type transpoter_location;

   typedef uint8_t _transpoter_shoes_type;
  _transpoter_shoes_type transpoter_shoes;





  typedef boost::shared_ptr< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> const> ConstPtr;

}; // struct transpoter_status_

typedef ::ShoesTranspoterPkg::transpoter_status_<std::allocator<void> > transpoter_status;

typedef boost::shared_ptr< ::ShoesTranspoterPkg::transpoter_status > transpoter_statusPtr;
typedef boost::shared_ptr< ::ShoesTranspoterPkg::transpoter_status const> transpoter_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ShoesTranspoterPkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/pi/roscatkin_ws/install_isolated/share/std_msgs/cmake/../msg'], 'ShoesTranspoterPkg': ['/home/pi/catkin_ws/src/ShoesTranspoterPkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "490dcc66345c67962ea080b1e85b562b";
  }

  static const char* value(const ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x490dcc66345c6796ULL;
  static const uint64_t static_value2 = 0x2ea080b1e85b562bULL;
};

template<class ContainerAllocator>
struct DataType< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ShoesTranspoterPkg/transpoter_status";
  }

  static const char* value(const ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 transpoter_id\n\
uint8 transpoter_location\n\
uint8 transpoter_shoes\n\
";
  }

  static const char* value(const ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transpoter_id);
      stream.next(m.transpoter_location);
      stream.next(m.transpoter_shoes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct transpoter_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ShoesTranspoterPkg::transpoter_status_<ContainerAllocator>& v)
  {
    s << indent << "transpoter_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.transpoter_id);
    s << indent << "transpoter_location: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.transpoter_location);
    s << indent << "transpoter_shoes: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.transpoter_shoes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHOESTRANSPOTERPKG_MESSAGE_TRANSPOTER_STATUS_H
