/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef StabiIF_H
#define StabiIF_H

#include "StabiMode.h"


/**

@author ike
@version 1.0
*/
class StabiIF
{
	/*
	User Defined Attribute
	*/
	/**
	モード
bit0=水平 
bit1=垂直
bit2=目標型、param2, param3の値有効
	*/
	public: short mode;
	/**
	目標方位(度)
	*/
	public: short dir;
	/**
	目標深度(cm)
	*/
	public: short depth;
	/*
	User Defined Method
	*/
};

#endif /* StabiIF_H */
