/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,EnumDataType.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef StabiMode_H
#define StabiMode_H



/**
スタビライザーのモード種類
@author ike
@version 1.0
*/
enum StabiMode
{
	/**
	方向をスタビライズする
	*/
	STABIMODE_DIR = 1,
	/**
	深さをスタビライズする。
	*/
	STABIMODE_DIVE = 2,
	/**
	指定方向と深さになるようスタビライズする。
	*/
	STABIMODE_TARGET = 4,
};

#endif /* StabiMode_H */
