/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboRTE_Model.cc.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */

#include "stdafx.h"
#include "BricRoboCOM_API.h"
#include "BricRoboRTE_API.h"
#include "BricRoboRTE_Model.h"
/*
TopLevel
*/
Boxfish TopLevel;

/*
ConfigParam
*/
void BricRoboRTE_ConfigParam()
{
	TopLevel.CTL.ConfigParam(0, 0, 512, 40*3);
	TopLevel.FLD.ConfigParam(500, 6);
	TopLevel.JET.ConfigParam(9, 2.55);
	TopLevel.LedLight.ConfigParam(8);
	TopLevel.LedStatus.ConfigParam(7);
	TopLevel.PEC_FIN.ConfigParam(6, 90, 1.0);
	TopLevel.POS.ConfigParam(0);
	TopLevel.TAIL_FIN.ConfigParam(5, 90, -1.0);
	TopLevel.TEL.ConfigParam(0);
	TopLevel.WD.ConfigParam(1);
	TopLevel.WP.ConfigParam(7);
}

/*
RTE-COM
*/
void BricRoboRTE_ConnectRteApi()
{
	TopLevel.CTL._portIF_command = &TaskCom_D1;
	TopLevel.CTL._portST_command = &TaskCom_D1_status;
	TopLevel.TEL._portAPI_command = Rte_Send_TEL_command;
	TopLevel.CTL._portIF_floodAlarm = &TaskCom_D2;
	TopLevel.CTL._portST_floodAlarm = &TaskCom_D2_status;
	TopLevel.FLD._portIF_alert = &TaskCom_D2;
	TopLevel.FLD._portST_alert = &TaskCom_D2_status;
	TopLevel.CTL._portIF_position = &TaskCom_D3;
	TopLevel.CTL._portST_position = &TaskCom_D3_status;
	TopLevel.POS._portAPI_out = Rte_Write_POS_out;
	TopLevel.CTL._portIF_waterDepth = &TaskCom_D4;
	TopLevel.CTL._portST_waterDepth = &TaskCom_D4_status;
	TopLevel.WD._portIF_out = &TaskCom_D4;
	TopLevel.WD._portST_out = &TaskCom_D4_status;
	TopLevel.CTL._portIF_waterPressure = &TaskCom_D5;
	TopLevel.CTL._portST_waterPressure = &TaskCom_D5_status;
	TopLevel.WP._portAPI_out = Rte_Write_WP_out;
	TopLevel.JET._portIF_in = &TaskCom_D6;
	TopLevel.JET._portST_in = &TaskCom_D6_status;
	TopLevel.CTL._portAPI_jetPower = Rte_Write_CTL_jetPower;
	TopLevel.LedLight._portIF_patternNo = &TaskCom_D7;
	TopLevel.LedLight._portST_patternNo = &TaskCom_D7_status;
	TopLevel.CTL._portIF_ledLight = &TaskCom_D7;
	TopLevel.CTL._portST_ledLight = &TaskCom_D7_status;
	TopLevel.LedStatus._portIF_patternNo = &TaskCom_D8;
	TopLevel.LedStatus._portST_patternNo = &TaskCom_D8_status;
	TopLevel.CTL._portIF_ledPattern = &TaskCom_D8;
	TopLevel.CTL._portST_ledPattern = &TaskCom_D8_status;
	TopLevel.MON._portIF_command = &TaskCom_D9;
	TopLevel.MON._portST_command = &TaskCom_D9_status;
	TopLevel.MON._portIF_jet = &TaskCom_D10;
	TopLevel.MON._portST_jet = &TaskCom_D10_status;
	TopLevel.MON._portIF_pecFin = &TaskCom_D11;
	TopLevel.MON._portST_pecFin = &TaskCom_D11_status;
	TopLevel.CTL._portAPI_pecFin = Rte_Write_CTL_pecFin;
	TopLevel.MON._portIF_position = &TaskCom_D12;
	TopLevel.MON._portST_position = &TaskCom_D12_status;
	TopLevel.MON._portIF_tailFin = &TaskCom_D13;
	TopLevel.MON._portST_tailFin = &TaskCom_D13_status;
	TopLevel.CTL._portAPI_tailFin = Rte_Write_CTL_tailFin;
	TopLevel.MON._portIF_waterPressure = &TaskCom_D14;
	TopLevel.MON._portST_waterPressure = &TaskCom_D14_status;
	TopLevel.PEC_FIN._portIF_in = &TaskCom_D15;
	TopLevel.PEC_FIN._portST_in = &TaskCom_D15_status;
	TopLevel.TAIL_FIN._portIF_in = &TaskCom_D16;
	TopLevel.TAIL_FIN._portST_in = &TaskCom_D16_status;
	TopLevel.TEL._portIF_navi = &TaskCom_D17;
	TopLevel.TEL._portST_navi = &TaskCom_D17_status;
	TopLevel.CTL._portIF_navi = &TaskCom_D17;
	TopLevel.CTL._portST_navi = &TaskCom_D17_status;
}
