/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboRTE_Model.h.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */
#ifndef ComsarRTE_Model_H
#define ComsarRTE_Model_H

/*
Used BricRobo CompositionType
*/
#include "../Boxfish.h"

extern Boxfish TopLevel;


extern void BricRoboRTE_ConnectRteApi();
extern void BricRoboRTE_ConfigParam();

#endif /* ComsarRTE_Model_H */
