/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboRTE_Task.cc.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */

#include "stdafx.h"
#include "BricRoboRTE_Model.h"
#include "BricRoboTask.h"
void TASK_BLANCE_Run()
{
	TopLevel.POS.Run();
	TopLevel.WP.Run();
	TopLevel.WD.Run();
	TopLevel.TEL.RunRx();
	TopLevel.CTL.Run();
	TopLevel.PEC_FIN.Run();
	TopLevel.TAIL_FIN.Run();
	TopLevel.JET.Run();
	TopLevel.TEL.RunTx();
}
void TASK_LED_Run()
{
	TopLevel.LedLight.Run();
	TopLevel.LedStatus.Run();
}
void TASK_UI_Run()
{
	TopLevel.MON.Run();
}


/**
姿勢制御用、ETロボコンの経験から25m秒周期ぐらいで十分反応できるだろう。
@author eguchi
@version 1.0
*/
BricRoboTask TASK_BLANCE = {25, 2, TASK_BLANCE_Run};

/**
LED専用タスク。点滅を制御するので周期は速い。
@author eguchi
@version 1.0
*/
BricRoboTask TASK_LED = {10, 0, TASK_LED_Run};

/**
ユーザーIF用。100m秒ぐらいで十分だろう。
@author eguchi
@version 1.0
*/
BricRoboTask TASK_UI = {100, 1, TASK_UI_Run};

BricRoboTask* taskList[3+1] =
{
	&TASK_BLANCE,
	&TASK_LED,
	&TASK_UI,
	(BricRoboTask*)0
};
