/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++.BricRoboRTE_API.h.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */
#ifndef ComsarRTE_API_H
#define ComsarRTE_API_H

/*
Interface
*/
#include "../../Common/CommandIF.h"
#include "../../BricRoboSketch/ValueIF.h"
#include "../../Common/PositionIF.h"
#include "../../Common/NaviIF.h"

/*
RTE API (SenderReceiverInterface)
*/
extern Std_ReturnType Rte_Send_TEL_command(CommandIF& v);
extern Std_ReturnType Rte_Write_POS_out(PositionIF& v);
extern Std_ReturnType Rte_Write_WP_out(ValueIF& v);
extern Std_ReturnType Rte_Write_CTL_jetPower(ValueIF& v);
extern Std_ReturnType Rte_Write_CTL_pecFin(ValueIF& v);
extern Std_ReturnType Rte_Write_CTL_tailFin(ValueIF& v);

/*
RTE API (ProcedureCallInterface)
*/


#endif /* ComsarRTE_API_H */
