/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboCOM_API.cc.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */

#include "stdafx.h"
#include "BricRoboCOM_API.h"

CommandIF TaskCom_D1;	/*CTL_command */
Std_ReturnType TaskCom_D1_status = RTE_E_NO_DATA;
ValueIF TaskCom_D2;	/*CTL_floodAlarm */
Std_ReturnType TaskCom_D2_status = RTE_E_NO_DATA;
PositionIF TaskCom_D3;	/*CTL_position */
Std_ReturnType TaskCom_D3_status = RTE_E_NO_DATA;
ValueIF TaskCom_D4;	/*CTL_waterDepth */
Std_ReturnType TaskCom_D4_status = RTE_E_NO_DATA;
ValueIF TaskCom_D5;	/*CTL_waterPressure */
Std_ReturnType TaskCom_D5_status = RTE_E_NO_DATA;
ValueIF TaskCom_D6;	/*JET_in */
Std_ReturnType TaskCom_D6_status = RTE_E_NO_DATA;
ValueIF TaskCom_D7;	/*LedLight_patternNo */
Std_ReturnType TaskCom_D7_status = RTE_E_NO_DATA;
ValueIF TaskCom_D8;	/*LedStatus_patternNo */
Std_ReturnType TaskCom_D8_status = RTE_E_NO_DATA;
CommandIF TaskCom_D9;	/*MON_command */
Std_ReturnType TaskCom_D9_status = RTE_E_NO_DATA;
ValueIF TaskCom_D10;	/*MON_jet */
Std_ReturnType TaskCom_D10_status = RTE_E_NO_DATA;
ValueIF TaskCom_D11;	/*MON_pecFin */
Std_ReturnType TaskCom_D11_status = RTE_E_NO_DATA;
PositionIF TaskCom_D12;	/*MON_position */
Std_ReturnType TaskCom_D12_status = RTE_E_NO_DATA;
ValueIF TaskCom_D13;	/*MON_tailFin */
Std_ReturnType TaskCom_D13_status = RTE_E_NO_DATA;
ValueIF TaskCom_D14;	/*MON_waterPressure */
Std_ReturnType TaskCom_D14_status = RTE_E_NO_DATA;
ValueIF TaskCom_D15;	/*PEC_FIN_in */
Std_ReturnType TaskCom_D15_status = RTE_E_NO_DATA;
ValueIF TaskCom_D16;	/*TAIL_FIN_in */
Std_ReturnType TaskCom_D16_status = RTE_E_NO_DATA;
NaviIF TaskCom_D17;	/*TEL_navi */
Std_ReturnType TaskCom_D17_status = RTE_E_NO_DATA;
