/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboRTE_API.cc.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */


#include "stdafx.h"
#include "BricRoboCOM_API.h"
#include "BricRoboRTE_API.h"
#include "BricRoboRTE_Model.h"

/*
RTE API (SenderReceiverInterface)
*/
/* RteApiID=3 */
Std_ReturnType Rte_Send_TEL_command(CommandIF& v)
{
	return (Std_ReturnType)(COM_Send_D1(v) | COM_Send_D9(v));
}

/* RteApiID=15 */
Std_ReturnType Rte_Write_POS_out(PositionIF& v)
{
	return (Std_ReturnType)(COM_Write_D3(v) | COM_Write_D12(v));
}

/* RteApiID=27 */
Std_ReturnType Rte_Write_WP_out(ValueIF& v)
{
	return (Std_ReturnType)(COM_Write_D5(v) | COM_Write_D14(v));
}

/* RteApiID=33 */
Std_ReturnType Rte_Write_CTL_jetPower(ValueIF& v)
{
	return (Std_ReturnType)(COM_Write_D6(v) | COM_Write_D10(v));
}

/* RteApiID=63 */
Std_ReturnType Rte_Write_CTL_pecFin(ValueIF& v)
{
	return (Std_ReturnType)(COM_Write_D11(v) | COM_Write_D15(v));
}

/* RteApiID=75 */
Std_ReturnType Rte_Write_CTL_tailFin(ValueIF& v)
{
	return (Std_ReturnType)(COM_Write_D13(v) | COM_Write_D16(v));
}

/*
RTE API (ProcedureCallInterface Assembly)
*/
/*
RTE API (ProcedureCallInterface Delegate Provider)
*/
/*
RTE API (ProcedureCallInterface Delegate Requester)
*/

