/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */
#ifndef StatusMonitor_H
#define StatusMonitor_H

#include "../../../Common/CommandIF.h"
#include "../../../BricRoboSketch/ValueIF.h"
#include "../../../Common/PositionIF.h"

/*
void StatusMonitor::Run()
{
	CommandIF command;
    Rte_Receive_command(command);
	ValueIF jet;
    Rte_Read_jet(jet);
	ValueIF pecFin;
    Rte_Read_pecFin(pecFin);
	PositionIF position;
    Rte_Read_position(position);
	ValueIF tailFin;
    Rte_Read_tailFin(tailFin);
	ValueIF waterPressure;
    Rte_Read_waterPressure(waterPressure);

}
*/


/**
各種情報を収集する。
@author eguchi
@version 1.0
*/
class StatusMonitor
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Receive_command(CommandIF) */
	BricRoboPortReceive(CommandIF,command);
	/**
	噴射パワー
	*/
	/* Rte_Read_jet(ValueIF) */
	BricRoboPortRead(ValueIF,jet);
	/**
	胸ビレの角度
	*/
	/* Rte_Read_pecFin(ValueIF) */
	BricRoboPortRead(ValueIF,pecFin);
	/**
	姿勢
	*/
	/* Rte_Read_position(PositionIF) */
	BricRoboPortRead(PositionIF,position);
	/**
	尾びれの角度
	*/
	/* Rte_Read_tailFin(ValueIF) */
	BricRoboPortRead(ValueIF,tailFin);
	/**
	水深
	*/
	/* Rte_Read_waterPressure(ValueIF) */
	BricRoboPortRead(ValueIF,waterPressure);
};

/* Procedure Template
*/

#endif /* StatusMonitor_H */
