/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */
#ifndef WaterDepthSensor_H
#define WaterDepthSensor_H

#include "../LowPassFilter/LowPassFilter25ms.h"
#include "../../../BricRoboSketch/ValueIF.h"

/*
void WaterDepthSensor::ConfigParam(int pin)
{
}
  void WaterDepthSensor::Run()
{
	ValueIF out;
    Rte_Write_out(out);

}
*/


/**

@author ike
@version 1.0
*/
class WaterDepthSensor
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: int _pin;
	/**
	
	*/
	public: LowPassFilter25ms LPF;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	
	*/
	public: void ConfigParam(int pin);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Write_out(ValueIF) */
	BricRoboPortWrite(ValueIF,out);
};

/* Procedure Template
*/

#endif /* WaterDepthSensor_H */
