/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef TeniboArduino_H
#define TeniboArduino_H

#include "Parts/AccelBuffer.h"
#include "../BricRoboSketch/DigitalOut.h"
#include "Parts/VoltSensor.h"
#include "Parts/TeniboArduinControlller.h"
#include "../JellyFish/Parts/XC10A/XC10A.h"
#include "../Common/Parts/LedDriver/LedDriver.h"
#include "Parts/Telecom.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "TeniboArduino.h"

void TeniboArduino::RunRsv()
{

}
void TeniboArduino::RunSend()
{

}
*/


/**

@author ike
@version 1.0
*/
class TeniboArduino
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/**
	
	*/
	public: AccelBuffer AB;
	/**
	
	*/
	public: DigitalOut BALL;
	/**
	
	*/
	public: VoltSensor BAT;
	/**
	
	*/
	public: TeniboArduinControlller CTRL;
	/**
	
	*/
	public: XC10A FR;
	/**
	
	*/
	public: LedDriver FRONTLED;
	/**
	
	*/
	public: XC10A STR1;
	/**
	
	*/
	public: XC10A STR2;
	/**
	
	*/
	public: Telecom TEL;
	/*
	Auto Generated Method
	*/
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void RunRsv()
	{
		TEL.RunRx();
		CTRL.Run();
		STR1.Run();
		STR2.Run();
		AB.Run();
		FR.Run();
	};
	/**
	
	*/
	public: void RunSend()
	{
		TEL.RunTx();
	};
	/*
	Port
	*/
};

/* Procedure Template
*/

#endif /* TeniboArduino_H */
