/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef Battery_H
#define Battery_H

#include "../../../BricRoboSketch/ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "Battery.h"

void Battery::ConfigParam(int8_t pin, float lowV, float highV)
{
}
  void Battery::Run()
{
	ValueIF v;
    Rte_Write_v(v);

}
*/


/**

@author ike
@version 1.0
*/
class Battery
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: int8_t _pin;
	/**
	アナログ入力値に掛けると電圧Vになる係数。
	*/
	private: float _K;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	
	@param lowV	
	@param highV	
	*/
	public: void ConfigParam(int8_t pin, float lowV, float highV);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Write_v(ValueIF) */
	BricRoboPortWrite(ValueIF,v);
};

/* Procedure Template
*/

#endif /* Battery_H */
