/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef VideoComStereo_H
#define VideoComStereo_H

#include "../TcpServer/TcpServer.h"
#include "../Camera/ImageFrame.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "VideoComStereo.h"

void VideoComStereo::ConfigParam(int portNo, int width, int height)
{
}
  void VideoComStereo::Run()
{
	ImageFrame imgLeft;
    Rte_Receive_imgLeft(imgLeft);
	ImageFrame imgRight;
    Rte_Receive_imgRight(imgRight);

}
*/


/**
カメラの映像を要求するクライアントに送信する。送信方法は、TCPサーバに接続してきたクライアントに対し、1枚の画像をJPEG圧縮して、32KB単位で分割して送信する。
2つのカメラ映像はLRで合成して横2倍になる。
@author eguchi
@version 1.0
*/
class VideoComStereo
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: TcpServer _server;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param portNo	
	@param width	
	@param height	
	*/
	public: void ConfigParam(int portNo, int width, int height);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Receive_imgLeft(ImageFrame) */
	BricRoboPortReceive(ImageFrame,imgLeft);
	/**
	
	*/
	/* Rte_Receive_imgRight(ImageFrame) */
	BricRoboPortReceive(ImageFrame,imgRight);
};

/* Procedure Template
*/

#endif /* VideoComStereo_H */
