/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef JellyFish_H
#define JellyFish_H

#include "Parts/Battery/Battery.h"
#include "Parts/CmdController/CmdController.h"
#include "Parts/MS580314BA/MS580314BA.h"
#include "Parts/XC10A/XC10A.h"
#include "../Common/Parts/FloodSensor/FloodSensor.h"
#include "../Common/Parts/LedDriverMini/LedMiniDriver.h"
#include "Parts/NoiseFilter/NoiseFilter.h"
#include "../Common/Parts/PositionSensor/PositionSensor.h"
#include "../Common/Parts/HMC5883L/Compass_HMC5883L.h"
#include "Parts/SwimController/SwimController.h"
#include "Parts/NaviSelector/NaviSelevtor.h"
#include "Parts/Telecom/Telecom.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "JellyFish.h"

void JellyFish::RunRsv()
{

}
void JellyFish::RunSend()
{

}
void JellyFish::RunBalance()
{

}
*/


/**

@author eguchi
@version 1.0
*/
class JellyFish
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/**
	
	*/
	public: Battery BAT;
	/**
	
	*/
	public: CmdController CTL;
	/**
	
	*/
	public: MS580314BA DEP;
	/**
	
	*/
	public: XC10A DIVEL;
	/**
	
	*/
	public: XC10A DIVER;
	/**
	
	*/
	public: FloodSensor FLD;
	/**
	
	*/
	public: LedMiniDriver LED;
	/**
	
	*/
	public: XC10A LEFT;
	/**
	
	*/
	public: NoiseFilter NF;
	/**
	
	*/
	public: PositionSensor POS;
	/**
	
	*/
	public: Compass_HMC5883L POS2;
	/**
	
	*/
	public: XC10A RIGHT;
	/**
	
	*/
	public: SwimController SC;
	/**
	
	*/
	public: NaviSelevtor SNV;
	/**
	
	*/
	public: Telecom TEL;
	/*
	Auto Generated Method
	*/
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void RunRsv()
	{
		TEL.RunRcv();
		BAT.Run();
		FLD.Run();
		CTL.RunRcv();
	};
	/**
	
	*/
	public: void RunSend()
	{
		CTL.RunSend();
		TEL.RunSend();
	};
	/**
	
	*/
	public: void RunBalance()
	{
		DEP.Run();
		POS.Run();
		POS2.Run();
		NF.Run();
		SNV.Run();
		SC.Run();
	};
	/*
	Port
	*/
};

/* Procedure Template
*/

#endif /* JellyFish_H */
