/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef Compass_HMC5883L_H
#define Compass_HMC5883L_H

#include "../../../BricRoboSketch/ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "Compass_HMC5883L.h"

void Compass_HMC5883L::ConfigParam(int dummy)
{
}
  void Compass_HMC5883L::Run()
{
	ValueIF dir;
    Rte_Write_dir(dir);

}
*/


/**
HMC5883Lで計測したX軸方向
（0－360度）
@author ike
@version 1.0
*/
class Compass_HMC5883L
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: HMC5883L compass;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param dummy	
	*/
	public: void ConfigParam(int dummy);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Write_dir(ValueIF) */
	BricRoboPortWrite(ValueIF,dir);
};

/* Procedure Template
*/

#endif /* Compass_HMC5883L_H */
