/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef ColorLedPattern_H
#define ColorLedPattern_H

#include "LedColor.h"
#include "../../../Common/Parts/LedDriver/LedPattern.h"


/**
カラーLEDを発行させるパターン
@author ike
@version 1.0
*/
class ColorLedPattern
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	public: int8_t color;
	/**
	
	*/
	public: int8_t patternNo;
	/*
	User Defined Method
	*/
};

#endif /* ColorLedPattern_H */
