/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,EnumDataType.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef LedColor_H
#define LedColor_H



/**
ビットに意味がある。他の色は組み合わせ。
0x01=Red
0x02=Blue
0x04=Green
@author ike
@version 1.0
*/
enum LedColor
{
	/**
	
	*/
	LEDCOLOR_BLACK = 0,
	/**
	
	*/
	LEDCOLOR_RED = 1,
	/**
	
	*/
	LEDCOLOR_BLUE = 2,
	/**
	
	*/
	LEDCOLOR_MAGENTA = 3,
	/**
	
	*/
	LEDCOLOR_GREEN = 4,
	/**
	
	*/
	LEDCOLOR_YELLOW = 5,
	/**
	
	*/
	LEDCOLOR_CYAN = 6,
	/**
	
	*/
	LEDCOLOR_WHITE = 7,
};

#endif /* LedColor_H */
