/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */
#ifndef Boxfish_H
#define Boxfish_H

#include "Parts/Controller/Controller.h"
#include "Parts/FloodSensor/FloodSensor.h"
#include "Parts/MotorDriver/MotorDriver.h"
#include "Parts/LedDriver/LedDriver.h"
#include "Parts/StatusMonitor/StatusMonitor.h"
#include "Parts/ServoMotor/ServoMotor.h"
#include "Parts/PositionSensor/PositionSensor.h"
#include "Parts/Telecom/Telecom.h"
#include "Parts/WaterDepthSensor/WaterDepthSensor.h"
#include "Parts/WaterPressureSensor/WaterPressureSensor.h"

/*
*/


/**

@author eguchi
@version 1.0
*/
class Boxfish
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/**
	
	*/
	public: Controller CTL;
	/**
	
	*/
	public: FloodSensor FLD;
	/**
	
	*/
	public: MotorDriver JET;
	/**
	
	*/
	public: LedDriver LedLight;
	/**
	
	*/
	public: LedDriver LedStatus;
	/**
	
	*/
	public: StatusMonitor MON;
	/**
	
	*/
	public: ServoMotor PEC_FIN;
	/**
	
	*/
	public: PositionSensor POS;
	/**
	
	*/
	public: ServoMotor TAIL_FIN;
	/**
	
	*/
	public: Telecom TEL;
	/**
	
	*/
	public: WaterDepthSensor WD;
	/**
	
	*/
	public: WaterPressureSensor WP;
	/*
	Auto Generated Method
	*/
	/*
	RunnableEntity
	*/
	/*
	Port
	*/
};

/* Procedure Template
*/

#endif /* Boxfish_H */
