/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef Telecom_H
#define Telecom_H

#include "../../../Common/JellyFish/JellyFishCommandIF.h"
#include "../../../Common/JellyFish/JellyFishNaviIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "Telecom.h"

void Telecom::ConfigParam(int dummy)
{
}
  void Telecom::RunRcv()
{
	JellyFishCommandIF command;
    Rte_Send_command(command);
	JellyFishNaviIF navi;
    Rte_Read_navi(navi);

}
void Telecom::RunSend()
{
	JellyFishCommandIF command;
    Rte_Send_command(command);
	JellyFishNaviIF navi;
    Rte_Read_navi(navi);

}
*/


/**

@author ike
@version 1.0
*/
class Telecom
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param dummy	
	*/
	public: void ConfigParam(int dummy);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void RunRcv();
	/**
	
	*/
	public: void RunSend();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Send_command(JellyFishCommandIF) */
	BricRoboPortSend(JellyFishCommandIF,command);
	/**
	
	*/
	/* Rte_Read_navi(JellyFishNaviIF) */
	BricRoboPortRead(JellyFishNaviIF,navi);
};

/* Procedure Template
*/

#endif /* Telecom_H */
