/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef ServoMotor_H
#define ServoMotor_H

#include "../../../BricRoboSketch/ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "ServoMotor.h"

void ServoMotor::ConfigParam(int8_t pin, int8_t center, float K)
{
}
  void ServoMotor::Run()
{
	ValueIF in;
    Rte_Read_in(in);

}
*/


/**
単位は度。

@author eguchi
@version 1.0
*/
class ServoMotor
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: Servo _servo;
	/**
	0度を指定したときのサーボホーンの角度(0..180)
	*/
	private: int8_t _center;
	/**
	入力値に掛ける値。-1を指定すれば回転方向が逆になる。
	*/
	private: float _K;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	PWMで使うピン番号
	@param center	0度を指定したときのサーボホーンの角度(0..180)
	@param K	入力値に掛ける値。-1を指定すれば回転方向が逆になる。
	*/
	public: void ConfigParam(int8_t pin, int8_t center, float K);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	サーボモーターの角度。
	*/
	/* Rte_Read_in(ValueIF) */
	BricRoboPortRead(ValueIF,in);
};

/* Procedure Template
*/

#endif /* ServoMotor_H */
