/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboRTE_Model.cc.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */

#include "stdafx.h"
#include "BricRoboCOM_API.h"
#include "BricRoboRTE_API.h"
#include "BricRoboRTE_Model.h"
/*
TopLevel
*/
JellyFish TopLevel;

/*
ConfigParam
*/
void BricRoboRTE_ConfigParam()
{
	TopLevel.BAT.ConfigParam(1, 4.26, 8.58);
	TopLevel.CTL.ConfigParam(512, 20*5);
	TopLevel.DEP.ConfigParam(0);
	TopLevel.DIVEL.ConfigParam(6, 0, 30);
	TopLevel.DIVER.ConfigParam(5, 0, 30);
	TopLevel.FLD.ConfigParam(0);
	TopLevel.LED.ConfigParam(13);
	TopLevel.LEFT.ConfigParam(7, 0, 40);
	TopLevel.NF.ConfigParam(2);
	TopLevel.POS.ConfigParam(0);
	TopLevel.POS2.ConfigParam(0);
	TopLevel.RIGHT.ConfigParam(8, 0, 40);
	TopLevel.SC.ConfigParam(0);
	TopLevel.SNV.ConfigParam(0);
	TopLevel.TEL.ConfigParam(0);
	TopLevel.SC.PID_DIR.ConfigParam(5, 1, 0, 1, 0, 1);
	TopLevel.SC.PID_DIVE.ConfigParam(3, 1, 0, 1, 0, 1);
	TopLevel.SC.PID_PITCH.ConfigParam(5, 1, 0, 1, 0, 1);
}

/*
RTE-COM
*/
void BricRoboRTE_ConnectRteApi()
{
	TopLevel.CTL._portIF_battery = &TaskCom_D1;
	TopLevel.CTL._portST_battery = &TaskCom_D1_status;
	TopLevel.BAT._portIF_v = &TaskCom_D1;
	TopLevel.BAT._portST_v = &TaskCom_D1_status;
	TopLevel.CTL._portIF_command = &TaskCom_D2;
	TopLevel.CTL._portST_command = &TaskCom_D2_status;
	TopLevel.TEL._portIF_command = &TaskCom_D2;
	TopLevel.TEL._portST_command = &TaskCom_D2_status;
	TopLevel.CTL._portIF_curNavi = &TaskCom_D3;
	TopLevel.CTL._portST_curNavi = &TaskCom_D3_status;
	TopLevel.SC._portIF_curNavi = &TaskCom_D3;
	TopLevel.SC._portST_curNavi = &TaskCom_D3_status;
	TopLevel.CTL._portIF_floodAlarm = &TaskCom_D4;
	TopLevel.CTL._portST_floodAlarm = &TaskCom_D4_status;
	TopLevel.FLD._portIF_value = &TaskCom_D4;
	TopLevel.FLD._portST_value = &TaskCom_D4_status;
	TopLevel.DIVEL._portIF_deadZone = &TaskCom_D5;
	TopLevel.DIVEL._portST_deadZone = &TaskCom_D5_status;
	TopLevel.CTL._portIF_deadZoneDiveL = &TaskCom_D5;
	TopLevel.CTL._portST_deadZoneDiveL = &TaskCom_D5_status;
	TopLevel.DIVEL._portIF_in = &TaskCom_D6;
	TopLevel.DIVEL._portST_in = &TaskCom_D6_status;
	TopLevel.SC._portIF_diveL = &TaskCom_D6;
	TopLevel.SC._portST_diveL = &TaskCom_D6_status;
	TopLevel.DIVER._portIF_deadZone = &TaskCom_D7;
	TopLevel.DIVER._portST_deadZone = &TaskCom_D7_status;
	TopLevel.CTL._portIF_deadZoneDiveR = &TaskCom_D7;
	TopLevel.CTL._portST_deadZoneDiveR = &TaskCom_D7_status;
	TopLevel.DIVER._portIF_in = &TaskCom_D8;
	TopLevel.DIVER._portST_in = &TaskCom_D8_status;
	TopLevel.SC._portIF_diveR = &TaskCom_D8;
	TopLevel.SC._portST_diveR = &TaskCom_D8_status;
	TopLevel.LED._portIF_patternNo = &TaskCom_D9;
	TopLevel.LED._portST_patternNo = &TaskCom_D9_status;
	TopLevel.CTL._portIF_led = &TaskCom_D9;
	TopLevel.CTL._portST_led = &TaskCom_D9_status;
	TopLevel.LEFT._portIF_deadZone = &TaskCom_D10;
	TopLevel.LEFT._portST_deadZone = &TaskCom_D10_status;
	TopLevel.CTL._portIF_deadZoneLeft = &TaskCom_D10;
	TopLevel.CTL._portST_deadZoneLeft = &TaskCom_D10_status;
	TopLevel.LEFT._portIF_in = &TaskCom_D11;
	TopLevel.LEFT._portST_in = &TaskCom_D11_status;
	TopLevel.SC._portIF_left = &TaskCom_D11;
	TopLevel.SC._portST_left = &TaskCom_D11_status;
	TopLevel.NF._portIF_in = &TaskCom_D12;
	TopLevel.NF._portST_in = &TaskCom_D12_status;
	TopLevel.POS2._portIF_dir = &TaskCom_D12;
	TopLevel.POS2._portST_dir = &TaskCom_D12_status;
	TopLevel.RIGHT._portIF_deadZone = &TaskCom_D13;
	TopLevel.RIGHT._portST_deadZone = &TaskCom_D13_status;
	TopLevel.CTL._portIF_deadZoneRight = &TaskCom_D13;
	TopLevel.CTL._portST_deadZoneRight = &TaskCom_D13_status;
	TopLevel.RIGHT._portIF_in = &TaskCom_D14;
	TopLevel.RIGHT._portST_in = &TaskCom_D14_status;
	TopLevel.SC._portIF_right = &TaskCom_D14;
	TopLevel.SC._portST_right = &TaskCom_D14_status;
	TopLevel.SC._portIF_ctrl = &TaskCom_D15;
	TopLevel.SC._portST_ctrl = &TaskCom_D15_status;
	TopLevel.CTL._portIF_ctrl = &TaskCom_D15;
	TopLevel.CTL._portST_ctrl = &TaskCom_D15_status;
	TopLevel.SC._portIF_navi = &TaskCom_D16;
	TopLevel.SC._portST_navi = &TaskCom_D16_status;
	TopLevel.SNV._portIF_navi = &TaskCom_D16;
	TopLevel.SNV._portST_navi = &TaskCom_D16_status;
	TopLevel.SC._portIF_pidParamDep = &TaskCom_D17;
	TopLevel.SC._portST_pidParamDep = &TaskCom_D17_status;
	TopLevel.CTL._portIF_pidParamDep = &TaskCom_D17;
	TopLevel.CTL._portST_pidParamDep = &TaskCom_D17_status;
	TopLevel.SC._portIF_pidParamDir = &TaskCom_D18;
	TopLevel.SC._portST_pidParamDir = &TaskCom_D18_status;
	TopLevel.CTL._portIF_pidParamDir = &TaskCom_D18;
	TopLevel.CTL._portST_pidParamDir = &TaskCom_D18_status;
	TopLevel.SC._portIF_stabi = &TaskCom_D19;
	TopLevel.SC._portST_stabi = &TaskCom_D19_status;
	TopLevel.CTL._portIF_stabi = &TaskCom_D19;
	TopLevel.CTL._portST_stabi = &TaskCom_D19_status;
	TopLevel.SNV._portIF_compass = &TaskCom_D20;
	TopLevel.SNV._portST_compass = &TaskCom_D20_status;
	TopLevel.NF._portIF_out = &TaskCom_D20;
	TopLevel.NF._portST_out = &TaskCom_D20_status;
	TopLevel.SNV._portIF_depth = &TaskCom_D21;
	TopLevel.SNV._portST_depth = &TaskCom_D21_status;
	TopLevel.DEP._portIF_out = &TaskCom_D21;
	TopLevel.DEP._portST_out = &TaskCom_D21_status;
	TopLevel.SNV._portIF_gyro = &TaskCom_D22;
	TopLevel.SNV._portST_gyro = &TaskCom_D22_status;
	TopLevel.POS._portIF_out = &TaskCom_D22;
	TopLevel.POS._portST_out = &TaskCom_D22_status;
	TopLevel.SNV._portIF_reset = &TaskCom_D23;
	TopLevel.SNV._portST_reset = &TaskCom_D23_status;
	TopLevel.CTL._portIF_resetNavi = &TaskCom_D23;
	TopLevel.CTL._portST_resetNavi = &TaskCom_D23_status;
	TopLevel.TEL._portIF_navi = &TaskCom_D24;
	TopLevel.TEL._portST_navi = &TaskCom_D24_status;
	TopLevel.CTL._portIF_navi = &TaskCom_D24;
	TopLevel.CTL._portST_navi = &TaskCom_D24_status;
	TopLevel.SC._portAPI_depth = Rte_Read_SC_depth;
}
