/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++.BricRoboRTE_API.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef ComsarRTE_API_H
#define ComsarRTE_API_H

/*
Interface
*/
#include "../../BricRoboSketch/ValueIF.h"
#include "../../Common/JellyFish/JellyFishCommandIF.h"
#include "../../Common/JellyFish/JellyFishNavi.h"
#include "../Parts/SwimController/SwimControllerIF.h"
#include "../../Common/PidParamIF.h"
#include "../Parts/CmdController/StabiIF.h"
#include "../../Common/PositionIF.h"
#include "../../Common/JellyFish/JellyFishNaviIF.h"

/*
RTE API (SenderReceiverInterface)
*/
extern Std_ReturnType Rte_Read_SC_depth(ValueIF& v);

/*
RTE API (ProcedureCallInterface)
*/


#endif /* ComsarRTE_API_H */
