/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboRTE_API.cc.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */


#include "stdafx.h"
#include "BricRoboCOM_API.h"
#include "BricRoboRTE_API.h"
#include "BricRoboRTE_Model.h"

/*
RTE API (SenderReceiverInterface)
*/
/* RteApiID=144 */
Std_ReturnType Rte_Read_SC_depth(ValueIF& v)
{
	return (Std_ReturnType)(COM_NotConnected(v));
}

/*
RTE API (ProcedureCallInterface Assembly)
*/
/*
RTE API (ProcedureCallInterface Delegate Provider)
*/
/*
RTE API (ProcedureCallInterface Delegate Requester)
*/

