/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboRTE_Model.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef ComsarRTE_Model_H
#define ComsarRTE_Model_H

/*
Used BricRobo CompositionType
*/
#include "../JellyFish.h"

extern JellyFish TopLevel;


extern void BricRoboRTE_ConnectRteApi();
extern void BricRoboRTE_ConfigParam();

#endif /* ComsarRTE_Model_H */
