/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboRTE_Task.cc.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */

#include "stdafx.h"
#include "BricRoboRTE_Model.h"
#include "BricRoboTask.h"
void TASK_BLANCE_Run()
{
	TopLevel.RunRsv();
	TopLevel.RunBalance();
	TopLevel.RunSend();
}
void TASK_LED_Run()
{
	TopLevel.LED.Run();
}
void TASK_PROP_Run()
{
	TopLevel.DIVEL.Run();
	TopLevel.DIVER.Run();
	TopLevel.RIGHT.Run();
	TopLevel.LEFT.Run();
}


/**
姿勢制御用、ハコフグちゃんの実績より50ms周期。サーボ＝ESCとの通信が20ms間隔だから、それ以上速くしても無駄。
@author eguchi
@version 1.0
*/
BricRoboTask TASK_BLANCE = {50, 2, TASK_BLANCE_Run};

/**
LED専用タスク。点滅を制御するので周期は速い。
@author eguchi
@version 1.0
*/
BricRoboTask TASK_LED = {10, 0, TASK_LED_Run};

/**
プロペラをゆっくりとPWM制御するためのタスク。
@author eguchi
@version 1.0
*/
BricRoboTask TASK_PROP = {50, 3, TASK_PROP_Run};

BricRoboTask* taskList[3+1] =
{
	&TASK_BLANCE,
	&TASK_LED,
	&TASK_PROP,
	(BricRoboTask*)0
};
