/*
	[NOTE] This file is automatically generated. Please do not hand-coded.

	Template:C++,BricRoboCOM_API.cc.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */

#include "stdafx.h"
#include "BricRoboCOM_API.h"

ValueIF TaskCom_D1;	/*CTL_battery */
Std_ReturnType TaskCom_D1_status = RTE_E_NO_DATA;
JellyFishCommandIF TaskCom_D2;	/*CTL_command */
Std_ReturnType TaskCom_D2_status = RTE_E_NO_DATA;
JellyFishNavi TaskCom_D3;	/*CTL_curNavi */
Std_ReturnType TaskCom_D3_status = RTE_E_NO_DATA;
ValueIF TaskCom_D4;	/*CTL_floodAlarm */
Std_ReturnType TaskCom_D4_status = RTE_E_NO_DATA;
ValueIF TaskCom_D5;	/*DIVEL_deadZone */
Std_ReturnType TaskCom_D5_status = RTE_E_NO_DATA;
ValueIF TaskCom_D6;	/*DIVEL_in */
Std_ReturnType TaskCom_D6_status = RTE_E_NO_DATA;
ValueIF TaskCom_D7;	/*DIVER_deadZone */
Std_ReturnType TaskCom_D7_status = RTE_E_NO_DATA;
ValueIF TaskCom_D8;	/*DIVER_in */
Std_ReturnType TaskCom_D8_status = RTE_E_NO_DATA;
ValueIF TaskCom_D9;	/*LED_patternNo */
Std_ReturnType TaskCom_D9_status = RTE_E_NO_DATA;
ValueIF TaskCom_D10;	/*LEFT_deadZone */
Std_ReturnType TaskCom_D10_status = RTE_E_NO_DATA;
ValueIF TaskCom_D11;	/*LEFT_in */
Std_ReturnType TaskCom_D11_status = RTE_E_NO_DATA;
ValueIF TaskCom_D12;	/*NF_in */
Std_ReturnType TaskCom_D12_status = RTE_E_NO_DATA;
ValueIF TaskCom_D13;	/*RIGHT_deadZone */
Std_ReturnType TaskCom_D13_status = RTE_E_NO_DATA;
ValueIF TaskCom_D14;	/*RIGHT_in */
Std_ReturnType TaskCom_D14_status = RTE_E_NO_DATA;
SwimControllerIF TaskCom_D15;	/*SC_ctrl */
Std_ReturnType TaskCom_D15_status = RTE_E_NO_DATA;
JellyFishNavi TaskCom_D16;	/*SC_navi */
Std_ReturnType TaskCom_D16_status = RTE_E_NO_DATA;
PidParamIF TaskCom_D17;	/*SC_pidParamDep */
Std_ReturnType TaskCom_D17_status = RTE_E_NO_DATA;
PidParamIF TaskCom_D18;	/*SC_pidParamDir */
Std_ReturnType TaskCom_D18_status = RTE_E_NO_DATA;
StabiIF TaskCom_D19;	/*SC_stabi */
Std_ReturnType TaskCom_D19_status = RTE_E_NO_DATA;
ValueIF TaskCom_D20;	/*SNV_compass */
Std_ReturnType TaskCom_D20_status = RTE_E_NO_DATA;
ValueIF TaskCom_D21;	/*SNV_depth */
Std_ReturnType TaskCom_D21_status = RTE_E_NO_DATA;
PositionIF TaskCom_D22;	/*SNV_gyro */
Std_ReturnType TaskCom_D22_status = RTE_E_NO_DATA;
ValueIF TaskCom_D23;	/*SNV_reset */
Std_ReturnType TaskCom_D23_status = RTE_E_NO_DATA;
JellyFishNaviIF TaskCom_D24;	/*TEL_navi */
Std_ReturnType TaskCom_D24_status = RTE_E_NO_DATA;
