/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,EnumDataType.h.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef RobotMode_H
#define RobotMode_H



/**
ロボット全体の状態
@author eguchi
@version 1.0
*/
enum RobotMode
{
	/**
	
	*/
	MODE_DIAG = 0,
	/**
	
	*/
	MODE_DIAG_ERROR = 1,
	/**
	
	*/
	MODE_LITSEN = 2,
	/**
	
	*/
	MODE_MANUAL = 3,
	/**
	
	*/
	MODE_AUTO = 4,
	/**
	
	*/
	MODE_COUNT = 5,
};

#endif /* RobotMode_H */
