/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef Telecom_H
#define Telecom_H

#include "../../TeniboCommon/TeniboCommandIF.h"
#include "../../TeniboCommon/TeniboNaviIF.h"
#include "../../TeniboCommon/TeniboComMagic.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "Telecom.h"

void Telecom::ConfigParam(int dummy)
{
}
  void Telecom::RunRx()
{
	TeniboCommandIF command;
    Rte_Send_command(command);
	TeniboNaviIF navi;
    Rte_Read_navi(navi);

}
void Telecom::RunTx()
{
	TeniboCommandIF command;
    Rte_Send_command(command);
	TeniboNaviIF navi;
    Rte_Read_navi(navi);

}
*/


/**

@author eguchi
@version 1.0
*/
class Telecom
{
	/*
	User Defined Attribute
	*/
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param dummy	
	*/
	public: void ConfigParam(int dummy);
	/*
	RunnableEntity
	*/
	/**
	受信処理を行う。
	*/
	public: void RunRx();
	/**
	送信処理を行う。
	*/
	public: void RunTx();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Send_command(TeniboCommandIF) */
	BricRoboPortSend(TeniboCommandIF,command);
	/**
	
	*/
	/* Rte_Read_navi(TeniboNaviIF) */
	BricRoboPortRead(TeniboNaviIF,navi);
};

/* Procedure Template
*/

#endif /* Telecom_H */
