/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef TeniboArduinControlller_H
#define TeniboArduinControlller_H

#include "RobotMode.h"
#include "../../BricRoboSketch/ValueIF.h"
#include "../../BricRoboSketch/HighLowIF.h"
#include "../../TeniboCommon/TeniboCommandIF.h"
#include "../../TeniboCommon/TeniboNaviIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "TeniboArduinControlller.h"

void TeniboArduinControlller::Run()
{
	ValueIF accel;
    Rte_Write_accel(accel);
	HighLowIF ballPick;
    Rte_Write_ballPick(ballPick);
	ValueIF battery;
    Rte_Read_battery(battery);
	TeniboCommandIF command;
    Rte_Receive_command(command);
	ValueIF frontLed;
    Rte_Send_frontLed(frontLed);
	TeniboNaviIF navi;
    Rte_Write_navi(navi);
	ValueIF steer1;
    Rte_Write_steer1(steer1);
	ValueIF steer2;
    Rte_Write_steer2(steer2);

}
 TeniboArduinControlller::TeniboArduinControlller()
{
}
  */


/**

@author ike
@version 1.0
*/
class TeniboArduinControlller
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: int _offlineCount = 0;
	/**
	
	*/
	private: ValueIF _accel;
	/**
	
	*/
	private: HighLowIF _ballPick;
	/**
	
	*/
	private: ValueIF _frontLed;
	/**
	
	*/
	private: ValueIF _steer1;
	/**
	
	*/
	private: ValueIF _steer2;
	/**
	
	*/
	private: RobotMode _mode;
	/*
	User Defined Method
	*/
	/**
	
	*/
	public:  TeniboArduinControlller();
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Write_accel(ValueIF) */
	BricRoboPortWrite(ValueIF,accel);
	/**
	
	*/
	/* Rte_Write_ballPick(HighLowIF) */
	BricRoboPortWrite(HighLowIF,ballPick);
	/**
	
	*/
	/* Rte_Read_battery(ValueIF) */
	BricRoboPortRead(ValueIF,battery);
	/**
	
	*/
	/* Rte_Receive_command(TeniboCommandIF) */
	BricRoboPortReceive(TeniboCommandIF,command);
	/**
	
	*/
	/* Rte_Send_frontLed(ValueIF) */
	BricRoboPortSend(ValueIF,frontLed);
	/**
	
	*/
	/* Rte_Write_navi(TeniboNaviIF) */
	BricRoboPortWrite(TeniboNaviIF,navi);
	/**
	
	*/
	/* Rte_Write_steer1(ValueIF) */
	BricRoboPortWrite(ValueIF,steer1);
	/**
	
	*/
	/* Rte_Write_steer2(ValueIF) */
	BricRoboPortWrite(ValueIF,steer2);
};

/* Procedure Template
*/

#endif /* TeniboArduinControlller_H */
