/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2018/09/19 14:45:51
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef VoltSensor_H
#define VoltSensor_H

#include "../../BricRoboSketch/ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "VoltSensor.h"

void VoltSensor::ConfigParam(int pin, float K)
{
}
  void VoltSensor::Run()
{
	ValueIF volt;
    Rte_Write_volt(volt);

}
*/


/**
初期化事にポートを入力にして、内部抵抗をONにするのが特徴。入力した値に係数Kを掛けて出力。
@author ike
@version 1.0
*/
class VoltSensor
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: int _pin;
	/**
	
	*/
	private: float _K = 1.0;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	
	@param K	
	*/
	public: void ConfigParam(int pin, float K);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Write_volt(ValueIF) */
	BricRoboPortWrite(ValueIF,volt);
};

/* Procedure Template
*/

#endif /* VoltSensor_H */
