/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,EnumDataType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef JellyFishStatusBit_H
#define JellyFishStatusBit_H



/**
ロボットの状態。
@author eguchi
@version 1.0
*/
enum JellyFishStatusBit
{
	/**
	緊急対処中
	*/
	JFS_EMERGENCY = 0x40,
	/**
	セーフティモードのON/OFF
	*/
	JFS_SAFETY_MODE = 0x80,
};

#endif /* JellyFishStatusBit_H */
