/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef JellyFishNavi_H
#define JellyFishNavi_H



/**
マルチローター用。
ロボットのなかで使うナビ情報
@author ike
@version 1.0
*/
class JellyFishNavi
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	public: int16_t dir;
	/**
	
	*/
	public: int16_t depth;
	/**
	
	*/
	public: int16_t pitch;
	/**
	
	*/
	public: int16_t roll;
	/*
	User Defined Method
	*/
};

#endif /* JellyFishNavi_H */
