/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef JellyFishNaviIF_H
#define JellyFishNaviIF_H

#include "../MAGIC_NO.h"
#include "JellyFishStatusBit.h"
#include "JellyFishNavi.h"


/**
ロボットからプロポに通知するナビ情報
@author ike
@version 1.0
*/
class JellyFishNaviIF
{
	/*
	User Defined Attribute
	*/
	/**
	電源バッテリ電圧。1,200は12.00V
	*/
	public: int16_t battery;
	/**
	漏水センサーの値。
	*/
	public: int16_t flood;
	/**
	ロボットの状態
	*/
	public: uint8_t status;
	/**
	現在のナビ値。
	*/
	public: JellyFishNavi curNavi;
	/*
	User Defined Method
	*/
};

#endif /* JellyFishNaviIF_H */
