/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,ClassDataType.h.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */
#ifndef LowPassFilter25ms_H
#define LowPassFilter25ms_H



/**
25m周期、カットオフ0.5秒のローパスフィルタ。三角関数の計算を省く為に係数は予め計算するタイプ。
内部計算精度はfloat。
@author eguchi
@version 1.0
*/
class LowPassFilter25ms
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: float _pre1;
	/**
	
	*/
	private: float _pre2;
	/*
	User Defined Method
	*/
	/**
	LPFを計算する。
	@param inp	
	*/
	public: int Calc(int inp);
	/**
	コンストラクタ
	*/
	public:  LowPassFilter25ms();
};

#endif /* LowPassFilter25ms_H */
