/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef VideoCom_H
#define VideoCom_H

#include "../TcpServer/TcpServer.h"
#include "../Camera/ImageFrame.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "VideoCom.h"

void VideoCom::ConfigParam(int portNo)
{
}
  void VideoCom::Run()
{
	ImageFrame img;
    Rte_Receive_img(img);

}
*/


/**
カメラの映像を要求するクライアントに送信する。
送信方法は、TCPサーバに接続してきたクライアントに対し、1枚の画像をJPEG圧縮して、32KB単位で分割して送信する。
@author eguchi
@version 1.0
*/
class VideoCom
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: TcpServer _server;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param portNo	
	*/
	public: void ConfigParam(int portNo);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Receive_img(ImageFrame) */
	BricRoboPortReceive(ImageFrame,img);
};

/* Procedure Template
*/

#endif /* VideoCom_H */
