/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef VideoRec_H
#define VideoRec_H

#include "../Camera/ImageFrame.h"
#include "VideoRecIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "VideoRec.h"

void VideoRec::ConfigParam(string videoPathOverlay, string videoPathOriginal, int elapse)
{
}
  void VideoRec::RunOverlay()
{
	ImageFrame chaOriginal;
    Rte_Receive_chaOriginal(chaOriginal);
	ImageFrame chaOverlay;
    Rte_Receive_chaOverlay(chaOverlay);
	VideoRecIF rec;
    Rte_Receive_rec(rec);
	VideoRecIF status;
    Rte_Write_status(status);

}
void VideoRec::RunOriginal()
{
	ImageFrame chaOriginal;
    Rte_Receive_chaOriginal(chaOriginal);
	ImageFrame chaOverlay;
    Rte_Receive_chaOverlay(chaOverlay);
	VideoRecIF rec;
    Rte_Receive_rec(rec);
	VideoRecIF status;
    Rte_Write_status(status);

}
*/


/**
recに0,1で指定録画開始、それ以外の値は録画停止
@author eguchi
@version 1.0
*/
class VideoRec
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: string _videoPathOverlay;
	/**
	
	*/
	private: string _videoPathOriginal;
	/**
	録画するフレームの時間間隔（ミリ秒）
	*/
	private: int _elapse;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param videoPathOverlay	ビデオファイルの場所とフォーマット。
例: {0}の部分には日付時間が入る。
/home/pi/my/Front{0}.mpeg

	@param videoPathOriginal	
	@param elapse	
	*/
	public: void ConfigParam(string videoPathOverlay, string videoPathOriginal, int elapse);
	/*
	RunnableEntity
	*/
	/**
	チャネル0

	*/
	public: void RunOverlay();
	/**
	チャネル1
	*/
	public: void RunOriginal();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Receive_chaOriginal(ImageFrame) */
	BricRoboPortReceive(ImageFrame,chaOriginal);
	/**
	
	*/
	/* Rte_Receive_chaOverlay(ImageFrame) */
	BricRoboPortReceive(ImageFrame,chaOverlay);
	/**
	
	*/
	/* Rte_Receive_rec(VideoRecIF) */
	BricRoboPortReceive(VideoRecIF,rec);
	/**
	
	*/
	/* Rte_Write_status(VideoRecIF) */
	BricRoboPortWrite(VideoRecIF,status);
};

/* Procedure Template
*/

#endif /* VideoRec_H */
