/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,SenderReceiverInterface.h.xsl
	Generated Date:2017/08/21 17:25:14
	Generater Name:BricRoboGen Ver:1.7.10.355  
 */
#ifndef VideoRecIF_H
#define VideoRecIF_H



/**

@author eguchi
@version 1.0
*/
class VideoRecIF
{
	/*
	User Defined Attribute
	*/
	/**
	チャネル0ビデオ録画指示
	*/
	public: bool channelOvl;
	/**
	チャネル0ビデオ録画指示
	*/
	public: bool channelOrg;
	/*
	User Defined Method
	*/
};

#endif /* VideoRecIF_H */
