/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2015/03/24 16:25:58
	Generater Name:BricRoboGen Ver:1.6.1.332  
 */
#ifndef WaterPressureSensor_H
#define WaterPressureSensor_H

#include "../LowPassFilter/LowPassFilter25ms.h"
#include "../../../BricRoboSketch/ValueIF.h"

/*
void WaterPressureSensor::ConfigParam(int pin)
{
}
  void WaterPressureSensor::Run()
{
	ValueIF out;
    Rte_Write_out(out);

}
*/


/**
内部に25ms周期のローパスフィルタを内蔵しているので、25m周期で使用すること。
@author eguchi
@version 1.0
*/
class WaterPressureSensor
{
	/*
	User Defined Attribute
	*/
	/**
	使用するアナログピン番号
	*/
	private: int _pin;
	/**
	
	*/
	private: LowPassFilter25ms LPF;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	使用するアナログピン番号
	*/
	public: void ConfigParam(int pin);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	
	*/
	/* Rte_Write_out(ValueIF) */
	BricRoboPortWrite(ValueIF,out);
};

/* Procedure Template
*/

#endif /* WaterPressureSensor_H */
