/*
	[NOTE] This file is automatically generated. Please do not hand-coded.
  
	Template:C++,CompositionType.h.xsl
	Generated Date:2017/01/23 13:47:44
	Generater Name:BricRoboGen Ver:1.7.10.351  
 */
#ifndef XC10A_H
#define XC10A_H

#include "../../../BricRoboSketch/ValueIF.h"

/* 実装のテンプレートとして利用してください
#include "stdafx.h"
#include "XC10A.h"

void XC10A::ConfigParam(int8_t pin, int8_t deadZone, int16_t range)
{
}
  void XC10A::Run()
{
	ValueIF deadZone;
    Rte_Receive_deadZone(deadZone);
	ValueIF in;
    Rte_Read_in(in);

}
*/


/**
ブラシレスモーター用ESCドライバ
XC10Aを不感帯なしで動かす


@author eguchi
@version 1.0
*/
class XC10A
{
	/*
	User Defined Attribute
	*/
	/**
	
	*/
	private: int8_t _deadZone;
	/**
	
	*/
	private: Servo _servo;
	/**
	
	*/
	private: int16_t _range;
	/*
	User Defined Method
	*/
	/*
	Auto Generated Attribute
	*/
	/*
	Auto Generated Method
	*/
	/**
	ConfigParam
	@param pin	PWMで使うピン番号
	@param deadZone	不感帯のレンジ。８はプラスマイナス８％を意味する。
	@param range	100%のうちどのレンジまで出力するか。
たとえば30の場合、100%を与えても30%しか出力がでない。
	*/
	public: void ConfigParam(int8_t pin, int8_t deadZone, int16_t range);
	/*
	RunnableEntity
	*/
	/**
	
	*/
	public: void Run();
	/*
	Port
	*/
	/**
	deadZoneを設定する
	*/
	/* Rte_Receive_deadZone(ValueIF) */
	BricRoboPortReceive(ValueIF,deadZone);
	/**
	
	*/
	/* Rte_Read_in(ValueIF) */
	BricRoboPortRead(ValueIF,in);
};

/* Procedure Template
*/

#endif /* XC10A_H */
